import { swallow } from '../utils/log';
/**
 * `execute` command — toolchain module. Extracted from execute.ts.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync, spawn } from 'child_process';
import chalk from 'chalk';

const dim = chalk.hex('#64748B');
const yellow = chalk.hex('#FBBF24');
const green = chalk.hex('#22C55E');
const cyan = chalk.hex('#22D3EE');
const red = chalk.hex('#EF4444');
const blue = chalk.hex('#60A5FA');
import { getCLICommand } from '../core/cli-detector';
import { hasApiErrorText } from './execute-helpers';
import { isAbortRequested, setAbortRequested } from './execute-abort';

import { IN_PROGRESS_FILE, InProgressEntry, InProgressFile, LocalCLIResult } from './execute-types';


export async function generateAgentRulesFiles(cwd: string): Promise<void> {
  const RULES = `# Project Agent Rules (auto-generated by MakeStudio)

These rules are MANDATORY for all code you write in this project.
Apply them to every task without exception.

---

## 1. BOILERPLATE STYLE COMPLIANCE — MANDATORY INSPECTION PROTOCOL

Before writing ANY code, complete this 4-step inspection:

**STEP 1 — Read boilerplate.md**
Read \`.makestudio/context/boilerplate.md\` to see what modules/entities/services exist.

**STEP 2 — Read at least 2 existing files of the SAME kind you are creating**
- Entity: \`fd -e ts "entity" api/src | head -3\` then Read the first 2
- Controller: \`fd -e ts "controller" api/src | head -3\` then Read the first 2
- Service: \`fd -e ts "service" api/src | head -3\` then Read the first 2
- DTO: \`fd -e ts "dto" api/src | head -3\` then Read the first 2
- Flutter Widget: \`fd -e dart "widget\\|screen" app/lib | head -3\` then Read the first 2
- Dart Model: \`fd -e dart "model" app/lib | head -3\` then Read the first 2

**STEP 3 — Extract 8 patterns**
- Import order (NestJS common first? External? Relative last?)
- Decorator usage (\`@Column({ type: 'varchar', nullable: true })\` vs bare \`@Column()\`)
- Naming (camelCase? kebab-case filenames? PascalCase classes?)
- Validation style (class-validator decorators, ValidationPipe?)
- Error handling (throw HttpException? custom exceptions?)
- Return types (explicit? Promise<T>?)
- Constructor injection pattern
- File header comments or JSDoc style

**STEP 4 — Match EXACTLY**
Use the IDENTICAL style as the files you read.
\`@Column({ type: 'varchar', length: 255, nullable: false })\` — EXACT form. NOT \`@Column('varchar', {...})\`.
The boilerplate is your source of truth. Your only job is to ADD features using the same patterns.

---

## 2. TOOLCHAIN RULES (NON-NEGOTIABLE)

- **Flutter/Dart**: ALWAYS use FVM. NEVER bare \`flutter\` or \`dart\` — they are NOT on PATH.
  - Correct: \`fvm flutter pub get\`, \`fvm dart analyze <path>\`, \`fvm flutter test\`
  - FVM binary at: \`~/fvm/versions/3.41.6/bin/flutter\`
  - Do NOT run \`which flutter\` or search for flutter — just use \`fvm\`
- **Dart analysis**: \`fvm dart analyze <path>\`. 0 issues = correct. Do NOT retry.
- **TypeScript**: NEVER \`tsc --noEmit\` (blows up memory). Use \`npx swc <file> -d /tmp/swc-check --strip-leading-paths\`.
- **DO NOT run \`npm install\` or \`flutter pub get\`** unless a NEW dependency is needed. Dependencies are already installed.
- **DO NOT run the backend** (npm run start, npm run dev) — it runs on remote VPS.
- **Commits**: English, no AI/Claude mention. Format: \`feat: [DUM-NNN] description\`

---

## 3. FILE STRUCTURE RULES

### BUNDLED FILE DETECTION — OVERRIDES PATH LITERALISM
Before creating any file, check if the techContext path is a BUNDLED filename.

**Bundled patterns that MUST be split:**
- TypeScript: \`<projectname>.dto.ts\`, \`<projectname>.entity.ts\`, \`*_dtos.ts\`, \`*_entities.ts\`, \`*_types.ts\`
- Dart: \`*_dtos.dart\`, \`*_models.dart\`, \`*_contracts.dart\`, \`*_entities.dart\`

When you detect a bundled path, do NOT create that file. Read the task description,
find the classes/DTOs mentioned, create ONE file per class:

- NestJS: UserDto → \`user.dto.ts\`, CreateUserDto → \`create-user.dto.ts\`, UserEntity → \`user.entity.ts\`
- Flutter: UserModel → \`user_model.dart\`, AppointmentDto → \`appointment_dto.dart\`

### FILE COUNT INVARIANT
If techContext lists N comma-separated paths, produce EXACTLY N files.
CORRECT: \`a.ts, b.ts, c.ts\` → 3 files.  WRONG: 1 file \`all.ts\` with 3 sections.

### PATH LITERALISM (non-bundled paths only)
\`app/lib/contracts/foo.dart\` → goes in \`app/lib/contracts/foo.dart\`.
Do NOT prepend \`core/\`, \`shared/\`, \`common/\`, or any directory not in techContext.

---

## 4. INTEGRATION RULES

1. Before writing any SHARED type/event/DTO/interface/enum — READ the relevant dependency DUM file (\`.makestudio/dums/dum_NNN.json\`). Do NOT guess.
2. Before choosing a file location — READ \`.makestudio/execution-state.json\` to see where previous DUMs put files. FOLLOW the convention.
3. If a type referenced in this task doesn't exist in any dependency DUM — emit a CONTRACT_GAP artifact and STOP. Do NOT invent it.
4. Any DUM number in text (\`see DUM-066\`) MUST be loaded from disk before acting. File: \`.makestudio/dums/dum_NNN.json\`.

---

## 5. NO PARALLEL SUB-AGENTS

You MUST implement each task SERIALLY in this single session.
DO NOT use the Agent or Task tool to dispatch parallel sub-agents that Edit/Write/MultiEdit files.

**Why:** parallel sub-agents run in isolated context. Each picks its own pattern
(different naming, directory, serialization). None can see what siblings are doing.
This produces divergent code in the same project — the biggest defect source in prior runs.

**ALLOWED:** Agent/Task for READ-ONLY exploration (Glob, Grep, Read, ripgrep).
**FORBIDDEN:** Agent/Task for Edit, Write, MultiEdit, NotebookEdit, Bash (shell mutations).

Do every file creation and edit YOURSELF, one after another, in sequence.

---

## 6. PROJECT CONTEXT FILES (read on demand)

### MANDATORY for every task
- \`.makestudio/context/boilerplate.md\` — what already exists (DO NOT recreate)
- \`.makestudio/context/stack.md\` — technologies, frameworks, versions
- \`.makestudio/context/spec.md\` — system overview and architecture

### DUM-specific
- \`.makestudio/dums/dum_NNN.json\` — full DUM spec for the current task
- \`.makestudio/execution-state.json\` — files created by completed DUMs + convention hints
- \`.makestudio/context/memory/\` — per-DUM JSON with full content

### Additional (read when relevant)
- \`.makestudio/context/requirements.md\` — functional requirements
- \`.makestudio/context/briefing.md\` — project brief and business goals
- \`.makestudio/context/visual-references.md\` — MANDATORY for UI tasks
- \`.makestudio/context/market-research.md\` — competitor analysis

---

## 7. REJECTION CRITERIA

Your work will be rejected if you:
- Skip the 4-step boilerplate inspection protocol
- Invent new patterns instead of copying existing ones
- Use bare \`flutter\`/\`dart\` commands
- Use \`tsc --noEmit\`
- Dispatch parallel sub-agents that write files
- Create bundled files (\`<projectname>.dto.ts\` with 10 classes inside)
- Ignore the file structure rules (FILE COUNT INVARIANT, PATH LITERALISM)
`;

  // Write the same rules to all three CLI-specific files
  const files = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md'];
  for (const f of files) {
    const filePath = path.join(cwd, f);
    // Only write if missing OR auto-generated (starts with our marker)
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
    const isAutoGenerated = existing.startsWith('# Project Agent Rules (auto-generated by MakeStudio)');
    if (!existing || isAutoGenerated) {
      fs.writeFileSync(filePath, RULES, 'utf8');
    }
  }
}

export async function ensureContextFiles(cwd: string, projectId: string, api: any, tenantId: string): Promise<void> {
  const ctxDir = path.join(cwd, '.makestudio', 'context');
  fs.mkdirSync(ctxDir, { recursive: true });

  // Check if critical files already exist
  const criticalFiles = ['boilerplate.md', 'spec.md', 'stack.md', 'briefing.md', 'requirements.md'];
  const missing = criticalFiles.filter(f => !fs.existsSync(path.join(ctxDir, f)));

  if (missing.length === 0) {
    console.log(`${dim('│')}  ${green('✓')} Context files OK (${criticalFiles.length} arquivos)`);
    return;
  }

  console.log(`${dim('│')}  ${yellow('!')} ${missing.length} context files ausentes — buscando do backend...`);

  try {
    const headers = { 'x-tenant-id': tenantId };
    const res = await api.get(`/dark-factory/projects/${projectId}`, { headers, timeout: 10_000 });
    const project = res.data;

    // Write each context file from project data
    const fileMap: Record<string, string> = {
      'briefing.md': project.briefing || project.description || '# Briefing\n\n(no briefing available)',
      'spec.md': project.spec || project.enrichedSpec || '# Spec\n\n(no spec available)',
      'stack.md': project.stack || '# Stack\n\n(no stack info available)',
      'requirements.md': '', // populated below
      'all-requirements.md': '',
      'boilerplate.md': project.boilerplateAnalysis || project.codebaseAnalysis || '',
      'market-research.md': project.marketResearch || '',
      'visual-references.md': project.visualReferences || '',
    };

    // Fetch requirements
    try {
      const reqRes = await api.get(`/dark-factory/projects/${projectId}/requirements`, { headers, timeout: 10_000 });
      const reqs = reqRes.data?.data || reqRes.data || [];
      if (reqs.length > 0) {
        fileMap['requirements.md'] = '# Requirements\n\n' + reqs.map((r: any, i: number) =>
          `## ${i + 1}. ${r.title || r.name}\n- ID: ${r.id}\n- Priority: ${r.priority || 'medium'}\n- ${r.description || ''}\n`,
        ).join('\n');
        fileMap['all-requirements.md'] = fileMap['requirements.md'];
      }
    } catch (err) { swallow(err); }

    // If boilerplate.md is empty, generate from codebase scan
    if (!fileMap['boilerplate.md']) {
      try {
        const apiDir = path.join(cwd, 'api', 'src');
        const appDir = path.join(cwd, 'app', 'lib');
        const lines: string[] = ['# Boilerplate Analysis\n'];

        if (fs.existsSync(apiDir)) {
          lines.push('## API (NestJS)\n');
          const entities = execSync(`find ${apiDir} -name "*.entity.ts" 2>/dev/null | head -20`, { shell: '/bin/sh' }).toString().trim();
          if (entities) lines.push('### Entities\n' + entities.split('\n').map(e => `- ${path.relative(cwd, e)}`).join('\n') + '\n');
          const controllers = execSync(`find ${apiDir} -name "*.controller.ts" 2>/dev/null | head -20`, { shell: '/bin/sh' }).toString().trim();
          if (controllers) lines.push('### Controllers\n' + controllers.split('\n').map(e => `- ${path.relative(cwd, e)}`).join('\n') + '\n');
          const services = execSync(`find ${apiDir} -name "*.service.ts" 2>/dev/null | head -20`, { shell: '/bin/sh' }).toString().trim();
          if (services) lines.push('### Services\n' + services.split('\n').map(e => `- ${path.relative(cwd, e)}`).join('\n') + '\n');
        }

        if (fs.existsSync(appDir)) {
          lines.push('## App (Flutter)\n');
          const dartFiles = execSync(`find ${appDir} -name "*.dart" 2>/dev/null | head -30`, { shell: '/bin/sh' }).toString().trim();
          if (dartFiles) lines.push('### Dart Files\n' + dartFiles.split('\n').map(e => `- ${path.relative(cwd, e)}`).join('\n') + '\n');
        }

        fileMap['boilerplate.md'] = lines.join('\n');
      } catch (err) { swallow(err); }
    }

    // Write files
    let written = 0;
    for (const [filename, content] of Object.entries(fileMap)) {
      if (!content) continue;
      const filePath = path.join(ctxDir, filename);
      if (!fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, content, 'utf8');
        written++;
      }
    }

    console.log(`${dim('│')}    ${green('✓')} ${written} context files gerados`);
  } catch (err: any) {
    console.log(`${dim('│')}    ${yellow('!')} Falha ao buscar contexto: ${err.message?.substring(0, 80)}`);
  }
}

export async function ensureToolchain(cwd: string): Promise<void> {
  // Flutter/FVM check
  const flutterDirs = ['app', 'mobile', 'flutter', '.'];
  for (const dir of flutterDirs) {
    const pubspec = path.join(cwd, dir, 'pubspec.yaml');
    if (!fs.existsSync(pubspec)) continue;

    const flutterRoot = path.join(cwd, dir);
    const fvmrc = path.join(flutterRoot, '.fvmrc');
    const fvmDir = path.join(flutterRoot, '.fvm');

    if (fs.existsSync(fvmrc) && fs.existsSync(fvmDir)) {
      console.log(`${dim('│')}  ${green('✓')} FVM configurado em ${dim(dir + '/')}`);
      continue;
    }

    // FVM not configured — auto-configure
    console.log(`${dim('│')}  ${yellow('!')} Flutter detectado em ${dim(dir + '/')} mas FVM nao configurado`);
    console.log(`${dim('│')}    ${dim('→ Configurando FVM automaticamente...')}`);

    try {
      // Find latest installed FVM version
      const fvmList = execSync('fvm list 2>&1', { timeout: 10_000 }).toString();
      const versionMatch = fvmList.match(/(\d+\.\d+\.\d+)/);
      if (!versionMatch) {
        console.log(`${dim('│')}    ${yellow('!')} Nenhuma versao Flutter instalada no FVM. Instale com: fvm install <version>`);
        continue;
      }
      const version = versionMatch[1];

      execSync(`fvm use ${version}`, { cwd: flutterRoot, timeout: 60_000, stdio: 'pipe' });
      console.log(`${dim('│')}    ${green('✓')} FVM configurado: Flutter ${version}`);

      // Run pub get
      execSync(`fvm flutter pub get`, { cwd: flutterRoot, timeout: 120_000, stdio: 'pipe' });
      console.log(`${dim('│')}    ${green('✓')} Dependencias instaladas (pub get)`);
    } catch (err: any) {
      console.log(`${dim('│')}    ${yellow('!')} Falha ao configurar FVM: ${err.message?.substring(0, 100)}`);
    }
  }

  // Node.js/NestJS check — ensure node_modules exist
  const apiDirs = ['api', 'backend', '.'];
  for (const dir of apiDirs) {
    const pkgJson = path.join(cwd, dir, 'package.json');
    const nodeModules = path.join(cwd, dir, 'node_modules');
    if (!fs.existsSync(pkgJson)) continue;

    if (fs.existsSync(nodeModules)) {
      console.log(`${dim('│')}  ${green('✓')} node_modules OK em ${dim(dir + '/')}`);
    } else {
      console.log(`${dim('│')}  ${yellow('!')} node_modules ausente em ${dim(dir + '/')} — instalando...`);
      try {
        execSync('npm install', { cwd: path.join(cwd, dir), timeout: 120_000, stdio: 'pipe' });
        console.log(`${dim('│')}    ${green('✓')} npm install concluido`);
      } catch (err: any) {
        console.log(`${dim('│')}    ${yellow('!')} npm install falhou: ${err.message?.substring(0, 100)}`);
      }
    }
  }
}

export async function runLocalCLI(cliName: string, prompt: string, cwd: string, _jobId?: string): Promise<LocalCLIResult | null> {
  return new Promise((resolve) => {
    const cliCmd = getCLICommand(cliName);
    const args: string[] = [];
    const isStreamJson = cliName === 'claude';
    const startTime = Date.now();

    if (cliName === 'claude') {
      args.push('-p', '--output-format', 'stream-json', '--verbose', '--dangerously-skip-permissions');
    } else if (cliName === 'codex') {
      args.push('exec', '--full-auto');
    } else if (cliName === 'gemini') {
      args.push('-y');
    }

    const proc = spawn(cliCmd, args, {
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env },
    });

    // SIGINT handler — kill child process and set abort flag
    const sigintHandler = () => {
      setAbortRequested(true);
      console.log(`\n    ${red('✗')} Abortando...`);
      proc.kill('SIGTERM');
      setTimeout(() => { try { proc.kill('SIGKILL'); } catch (err) { swallow(err); } }, 3000);
    };
    process.on('SIGINT', sigintHandler);

    proc.stdin.write(prompt);
    proc.stdin.end();

    let allOutput = '';
    let resultText = '';
    let lineBuffer = '';
    let toolCalls = 0;
    let lastActivityAt = Date.now();
    let hasApiError = false;

    const heartbeatTimer = setInterval(() => {
      const elapsed = Math.round((Date.now() - startTime) / 1000);
      const mins = Math.floor(elapsed / 60);
      const secs = elapsed % 60;
      const silentSecs = Math.round((Date.now() - lastActivityAt) / 1000);
      const elapsedStr = mins > 0 ? `${mins}m${String(secs).padStart(2, '0')}s` : `${secs}s`;
      const silentHint = silentSecs >= 30 ? dim(` · sem output há ${silentSecs}s`) : '';
      process.stdout.write(`\r  ${dim('⏳')} ${cyan(cliName.toUpperCase())} trabalhando... ${dim(elapsedStr)} · ${dim(`${toolCalls} tool calls`)}${silentHint}   `);
    }, 3_000);

    const markActivity = () => { lastActivityAt = Date.now(); };

    proc.stdout.on('data', (data: Buffer) => {
      const chunk = data.toString();
      allOutput += chunk;
      if (hasApiErrorText(chunk)) hasApiError = true;
      markActivity();

      if (isStreamJson) {
        lineBuffer += chunk;
        const lines = lineBuffer.split('\n');
        lineBuffer = lines.pop() || '';
        for (const line of lines) {
          if (!line.trim()) continue;
          try {
            const parsed = JSON.parse(line);
            if (parsed.type === 'assistant' && Array.isArray(parsed.message?.content)) {
              for (const block of parsed.message.content) {
                if (block.type === 'tool_use') {
                  toolCalls++;
                  const detail = block.input?.command?.substring(0, 80)
                    || block.input?.file_path
                    || block.input?.pattern
                    || block.input?.query?.substring(0, 80)
                    || '';
                  process.stdout.write('\r' + ' '.repeat(90) + '\r');
                  console.log(`    ${dim('·')} ${cyan(block.name)} ${dim(detail)}`);
                }
                if (block.type === 'text' && block.text?.trim()) {
                  const text = block.text.trim();
                  if (text.length > 0 && text.length < 400) {
                    process.stdout.write('\r' + ' '.repeat(90) + '\r');
                    console.log(`    ${dim(text)}`);
                  }
                }
              }
            }
            if (parsed.type === 'result' && parsed.result) resultText = parsed.result;
          } catch (err) { swallow(err); }
        }
      } else {
        const lines = chunk.split('\n');
        for (const line of lines) {
          const t = line.trim();
          if (t.length > 3 && t.length < 300) {
            process.stdout.write('\r' + ' '.repeat(90) + '\r');
            console.log(`    ${dim(t)}`);
          }
        }
      }
    });

    proc.stderr.on('data', (data: Buffer) => {
      const chunk = data.toString();
      allOutput += chunk;
      if (hasApiErrorText(chunk)) hasApiError = true;
      const lines = chunk.split('\n');
      for (const line of lines) {
        const t = line.trim();
        if (t && !t.includes('ExperimentalWarning') && !t.includes('DeprecationWarning')) {
          process.stdout.write('\r' + ' '.repeat(90) + '\r');
          console.log(`    ${yellow('!')} ${dim(t.substring(0, 150))}`);
        }
      }
    });

    proc.on('close', (code) => {
      clearInterval(heartbeatTimer);
      process.removeListener('SIGINT', sigintHandler);
      process.stdout.write('\r' + ' '.repeat(90) + '\r');
      if (lineBuffer.trim()) {
        try {
          const parsed = JSON.parse(lineBuffer);
          if (parsed.type === 'result' && parsed.result) resultText = parsed.result;
        } catch (err) { swallow(err); }
      }
      const elapsed = Math.round((Date.now() - startTime) / 1000);
      if (isAbortRequested()) {
        console.log(`    ${red(`✗ ${cliName.toUpperCase()} abortado após ${elapsed}s`)}`);
      } else {
        console.log(`    ${dim(`✓ ${cliName.toUpperCase()} concluído em ${elapsed}s · ${toolCalls} tool calls`)}`);
      }
      const output = resultText || allOutput;
      const exitCode = typeof code === 'number' ? code : 1;
      if (exitCode !== 0 && !output) {
        resolve(null);
        return;
      }
      resolve({
        output,
        exitCode,
        toolCalls,
        hasApiError,
      });
    });

    proc.on('error', () => { clearInterval(heartbeatTimer); process.removeListener('SIGINT', sigintHandler); resolve(null); });
  });
}
