/**
 * Slash command handlers — agent topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `AGENT_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashPlan(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // User-invoked plan mode. Thin wrapper around the EnterPlanMode /
  // ExitPlanMode / PlanModeStatus tools so the agent-initiated path
  // (via tool call) and the user-initiated path stay in lockstep.
  //   /plan             → enter plan mode
  //   /plan status      → show current plan mode state
  //   /plan exit|done   → request approval + exit (same flow as tool)
  //   /plan <text>      → enter plan mode (the text is a hint the user
  //                       would then re-submit as their first message)
  const { executeAdvancedTool, isPlanModeActive } = require('../ai/advanced-tools');
  const sub = rest[0];

  if (sub === 'status') {
    const r = await executeAdvancedTool('PlanModeStatus', {}, ctx);
    console.log('  ' + r.split('\n').join('\n  '));
    return;
  }

  if (sub === 'exit' || sub === 'done' || sub === 'stop') {
    if (!isPlanModeActive(ctx)) { console.log(`  ${dim('(not in plan mode)')}`); return; }
    const r = await executeAdvancedTool('ExitPlanMode', {}, ctx);
    console.log('  ' + r.split('\n').join('\n  '));
    return;
  }

  if (isPlanModeActive(ctx)) {
    console.log(`  ${yellow('!')} Already in plan mode. Use ${cyan('/plan exit')} to request approval and leave.`);
    return;
  }
  const r = await executeAdvancedTool('EnterPlanMode', {}, ctx);
  console.log('  ' + r.split('\n').join('\n  '));
  const hint = rest.join(' ').trim();
  if (hint) {
    console.log('');
    console.log(`  ${dim('Next: send your planning question (e.g. "plan ' + hint + '"). Write/Edit/Bash are blocked while in plan mode.')}`);
  }
}

async function handleSlashCoordinator(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // /coordinator                         — activate coordinator mode
  // /coordinator off                     — deactivate coordinator mode
  // /coordinator resume <session-id>     — resume a saved session
  // /coordinator monitor <mode>          — change monitor mode (dashboard|linear|silent)
  const sub = rest[0];

  if (!sub) {
    // /coordinator — activate
    try {
      const result = await executeCoordinatorTool('coordinator_activate', {}, ctx);
      let parsed: any;
      try { parsed = JSON.parse(result); } catch { parsed = null; }
      if (parsed?.ok) {
        console.log(`[coordinator] activated — session ${parsed.sessionId}`);
        console.log(`[coordinator] scratchpad: ${parsed.scratchpad}`);
        console.log(`[coordinator] monitor: ${parsed.monitor}`);
      } else {
        console.log(`[coordinator] ${parsed?.message || result}`);
      }
    } catch (e: any) {
      console.log(`[coordinator] error: ${e.message || e}`);
    }
    return;
  }

  if (sub === 'off') {
    // /coordinator off — deactivate
    try {
      const result = await executeCoordinatorTool('coordinator_deactivate', {}, ctx);
      let parsed: any;
      try { parsed = JSON.parse(result); } catch { parsed = null; }
      if (parsed?.ok) {
        console.log(`[coordinator] deactivated (session ${parsed.sessionId})`);
      } else {
        console.log(`[coordinator] ${parsed?.message || result}`);
      }
    } catch (e: any) {
      console.log(`[coordinator] error: ${e.message || e}`);
    }
    return;
  }

  if (sub === 'resume') {
    // /coordinator resume <session-id>
    const sessionId = rest.slice(1).join(' ').trim();
    if (!sessionId) {
      console.log(`[coordinator] Usage: /coordinator resume <session-id>`);
      return;
    }
    if (ctx.coordinatorActive) {
      console.log(`[coordinator] coordinator already active (session: ${ctx.coordinatorSessionId}). Use /coordinator off first.`);
      return;
    }
    ctx.coordinatorActive = true;
    ctx.coordinatorSessionId = sessionId;
    ctx.coordinatorWorkers = new Map();
    const scratchDir = path.join(os.homedir(), '.makestudio', 'scratch', sessionId);
    fs.mkdirSync(scratchDir, { recursive: true });
    console.log(`[coordinator] resumed session ${sessionId}`);
    console.log(`[coordinator] scratchpad: ${scratchDir}`);
    return;
  }

  if (sub === 'monitor') {
    // /coordinator monitor <mode>
    const mode = rest[1];
    const validModes: Array<'dashboard' | 'linear' | 'silent'> = ['dashboard', 'linear', 'silent'];
    if (!mode) {
      console.log(`[coordinator] Missing monitor mode. Valid: dashboard, linear, silent`);
      return;
    }
    if (!validModes.includes(mode as any)) {
      console.log(`[coordinator] Invalid monitor mode: "${mode}". Valid: dashboard, linear, silent`);
      return;
    }
    ctx.coordinatorMonitor = mode as 'dashboard' | 'linear' | 'silent';
    console.log(`[coordinator] monitor mode set to: ${mode}`);
    return;
  }

  console.log(`[coordinator] Usage: /coordinator [off | resume <id> | monitor <dashboard|linear|silent>]`);
}

async function handleSlashOutputStyle(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const valid: string[] = ['default', 'terse', 'verbose', 'explain', 'code-only'];
  const arg = (rest[0] || '').toLowerCase();
  if (!arg) {
    const s = loadSettings();
    console.log(`  ${dim('Current:')} ${cyan(s.outputStyle)}`);
    console.log(`  ${dim('Options:')} ${valid.map(v => cyan(v)).join(', ')}`);
    console.log(`  ${dim('  default:')}  balanced prose + code`);
    console.log(`  ${dim('  terse:')}    ultra-brief, no prose`);
    console.log(`  ${dim('  verbose:')}  explain every step`);
    console.log(`  ${dim('  explain:')}  didactic — use when learning a new codebase`);
    console.log(`  ${dim('  code-only:')} return only code, no prose`);
    return;
  }
  if (!valid.includes(arg)) {
    console.log(`  ${yellow('!')} Invalid style. Options: ${valid.join(', ')}`);
    return;
  }
  saveSettings({ outputStyle: arg as any });
  console.log(`  ${green('✓')} Output style: ${cyan(arg)}`);
}

async function handleSlashMemory(sc: SlashContext): Promise<void> {
  const { argsStr, rest } = sc;
  const sub = rest[0]?.toLowerCase();
  const { loadAllTopics, deleteTopic, saveTopic, regenerateIndex } = require('../memory');
  if (!sub || sub === 'list') {
    const topics = loadAllTopics();
    console.log();
    if (topics.length === 0) {
      console.log(`  ${dim('Nenhuma memoria salva.')}`);
    } else {
      console.log(`  ${chalk.white.bold('Memoria persistente')}`);
      console.log();
      for (const t of topics.sort((a: any, b: any) => b.accessCount - a.accessCount).slice(0, 30)) {
        const tags = t.tags.length > 0 ? dim(` [${t.tags.join(', ')}]`) : '';
        console.log(`  ${cyan(t.name)}${tags} ${dim(`(${t.accessCount} acessos)`)}`);
      }
    }
    console.log();
  } else if (sub === 'save' && rest.length >= 3) {
    const name = rest[1];
    const body = argsStr.replace(/^save\s+\S+\s+/, '');
    saveTopic({ name, body, tags: [] });
    console.log(`  ${green('✓')} Memoria ${cyan(name)} salva.`);
  } else if (sub === 'delete' && rest[1]) {
    const ok = deleteTopic(rest[1]);
    console.log(ok ? `  ${green('✓')} Removido` : `  ${yellow('!')} Nao encontrado`);
  } else if (sub === 'rebuild') {
    regenerateIndex();
    console.log(`  ${green('✓')} Index regenerado.`);
  } else if (sub === 'prune') {
    const { pruneStale, getStaleCount } = require('../memory');
    const staleCount = getStaleCount();
    console.log(`  ${dim('Topicos stale (>180d sem acesso):')} ${yellow(String(staleCount))}`);
    const removed = pruneStale();
    console.log(`  ${green('✓')} ${removed} topico(s) removido(s).`);
  } else if (sub === 'similar') {
    const { findSimilarTopics } = require('../memory');
    const pairs = findSimilarTopics(0.5);
    console.log();
    if (pairs.length === 0) {
      console.log(`  ${dim('Nenhum par similar encontrado.')}`);
    } else {
      console.log(`  ${chalk.white.bold('Topicos similares (considere merge)')}`);
      console.log();
      for (const p of pairs.slice(0, 10)) {
        const pct = Math.round(p.similarity * 100);
        console.log(`  ${cyan(String(pct).padStart(3) + '%')} ${p.a.name} ${dim('↔')} ${p.b.name}`);
      }
    }
    console.log();
  } else if (sub === 'sync' && rest[1]) {
    const targetPeerId = rest[1];
    try {
      const { pullMemoryFromPeer } = require('../cluster/client');
      const res = await pullMemoryFromPeer(targetPeerId);
      const conflicts = res.applied.filter((a: any) => a.outcome === 'conflict').length;
      console.log();
      console.log(`  ${green('✓')} sync com ${cyan(targetPeerId)}: ${res.pulled} pulled, ${res.skipped} skipped, ${conflicts} conflicts`);
      for (const a of res.applied) {
        const icon = a.outcome === 'kept-remote' ? green('+') : a.outcome === 'conflict' ? yellow('⚠') : dim('=');
        console.log(`    ${icon} ${a.name} ${dim(`(${a.outcome})`)}`);
      }
      if (conflicts > 0) {
        console.log(`  ${yellow('!')} Resolva conflitos com: ${cyan('/memory conflicts')}`);
      }
      console.log();
    } catch (err: any) {
      console.log(`  ${red('✗')} sync falhou: ${err.message || err}`);
    }
  } else if (sub === 'conflicts') {
    const topics = loadAllTopics();
    const conflicts = topics.filter((t: any) => t.name && t.name.includes('(conflict from'));
    console.log();
    if (conflicts.length === 0) {
      console.log(`  ${dim('Nenhum conflito.')}`);
    } else {
      console.log(`  ${chalk.white.bold('Conflitos de sync')} ${dim('(ambas as versões mantidas)')}`);
      console.log();
      for (const c of conflicts) {
        const baseName = c.name.replace(/ \(conflict from .*$/, '');
        console.log(`  ${yellow('⚠')} ${cyan(baseName)}  ${dim(c.name.match(/\(conflict from (.*)\)/)?.[1] ?? '')}`);
        console.log(`    ${dim('preview:')} ${c.body.split('\n').find((l: string) => l.trim()) || ''}`);
      }
      console.log();
      console.log(`  ${dim('Para resolver: edite o tópico principal manualmente e apague o conflict-* com')} ${cyan('/memory delete')}`);
    }
    console.log();
  } else {
    console.log(`  ${dim('Uso:')}`);
    console.log(`    ${cyan('/memory list')}              ${dim('listar topicos')}`);
    console.log(`    ${cyan('/memory save ...')}          ${dim('salvar novo topico')}`);
    console.log(`    ${cyan('/memory delete ...')}        ${dim('apagar topico (tombstone propaga via sync)')}`);
    console.log(`    ${cyan('/memory rebuild')}           ${dim('regenerar index')}`);
    console.log(`    ${cyan('/memory prune')}             ${dim('remover topicos stale (>180d)')}`);
    console.log(`    ${cyan('/memory similar')}           ${dim('detectar topicos similares')}`);
    console.log(`    ${cyan('/memory sync <peer-id>')}    ${dim('puxar memory de um peer do cluster')}`);
    console.log(`    ${cyan('/memory conflicts')}         ${dim('listar conflitos concorrentes pendentes')}`);
  }
}

async function handleSlashMcp(sc: SlashContext): Promise<void> {
  const { ctx, rest, command } = sc;
  const sub = rest[0]?.toLowerCase();
  const { initMcpServers, listMcpServers, readMcpResource, getMcpPrompt } = require('../mcp');
  if (!sub || sub === 'list') {
    await initMcpServers(ctx.cwd);
    const servers = listMcpServers();
    console.log();
    if (servers.length === 0) {
      console.log(`  ${dim('Nenhum MCP server configurado.')}`);
      console.log(`  ${dim('Configure em')} ${cyan('~/.makestudio/mcp.json')} ${dim('ou')} ${cyan('.makestudio/mcp.json')}`);
      console.log(`  ${dim('Exemplo:')} ${cyan('{"servers": {"linear": {"command": "npx", "args": ["-y", "@linear/mcp"]}}}')}`);
    } else {
      console.log(`  ${chalk.white.bold('MCP Servers')}`);
      console.log();
      for (const s of servers) {
        console.log(`  ${green('●')} ${cyan(s.name)} ${dim(`(${s.tools} tools, ${s.resources} resources, ${s.prompts} prompts)`)}`);
      }
    }
    console.log();
  } else if (sub === 'resources') {
    const { resources } = await initMcpServers(ctx.cwd);
    console.log();
    console.log(`  ${chalk.white.bold('MCP Resources')}`);
    console.log();
    for (const r of resources.slice(0, 30)) {
      console.log(`  ${dim(r.serverName)}: ${cyan(r.uri)} ${dim('—')} ${r.description || r.name}`);
    }
    console.log();
  } else if (sub === 'read' && rest[1]) {
    const content = await readMcpResource(rest[1]);
    console.log();
    console.log(content.slice(0, 3000));
    console.log();
  } else if (sub === 'prompts') {
    const { prompts } = await initMcpServers(ctx.cwd);
    console.log();
    console.log(`  ${chalk.white.bold('MCP Prompts')}`);
    console.log();
    for (const p of prompts) {
      console.log(`  ${cyan(p.name)} ${dim('—')} ${p.description || '(no description)'}`);
    }
    console.log();
  } else {
    console.log(`  ${dim('Uso:')}`);
    console.log(`    ${cyan('/mcp list')}`);
    console.log(`    ${cyan('/mcp resources')}`);
    console.log(`    ${cyan('/mcp read <uri>')}`);
    console.log(`    ${cyan('/mcp prompts')}`);
  }
}

async function handleSlashAgents(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Lists custom agents registered in ~/.claude/agents, ~/.makestudio/agents,
  // <cwd>/.claude/agents, <cwd>/.makestudio/agents.
  const { loadCustomAgents } = require('../ai/custom-agents');
  const agents = loadCustomAgents(ctx.cwd);
  if (agents.length === 0) {
    console.log(`  ${dim('Nenhum custom agent encontrado.')}`);
    console.log(`  ${dim('Crie um em:')} ${cyan('~/.makestudio/agents/<nome>.md')}`);
    console.log(`  ${dim('ou')} ${cyan(ctx.cwd + '/.claude/agents/<nome>.md')}`);
    console.log(dim('  Formato:'));
    console.log(dim('    ---'));
    console.log(dim('    name: my-reviewer'));
    console.log(dim('    description: what it does'));
    console.log(dim('    tools: [Read, Glob, Grep]'));
    console.log(dim('    ---'));
    console.log(dim('    Você é um ... (system prompt do subagent)'));
    return;
  }
  console.log(`  ${dim('Custom agents disponíveis:')}`);
  for (const a of agents) {
    const tools = a.tools?.length ? `  ${dim('[')} ${cyan(a.tools.join(', '))} ${dim(']')}` : '';
    console.log(`    ${cyan(a.name.padEnd(22))} ${dim('·')} ${a.description}${tools}`);
    console.log(`    ${dim(a.source + ' · ' + a.path)}`);
  }
  console.log();
  console.log(`  ${dim('Uso:')} ${cyan('/agent <nome> <task>')} ${dim('ou peça em linguagem natural')}`);
}

async function handleSlashAgent(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // Direct invocation of a custom subagent — bypasses the main LLM.
  // Saves tokens compared to "o LLM decide" because the user prompt
  // goes straight to the subagent's own context.
  let agentName = rest[0];
  let task = rest.slice(1).join(' ').trim();

  // No agent name → open fuzzy picker (Fase 3.3). User picks visually,
  // then we prompt inline for the task string.
  if (!agentName) {
    const { loadCustomAgents } = require('../ai/custom-agents');
    const agents = loadCustomAgents(ctx.cwd);
    if (agents.length === 0) {
      console.log(`  ${yellow('!')} Nenhum custom agent cadastrado.`);
      console.log(`  ${dim('Crie em')} ${cyan('~/.makestudio/agents/<nome>.md')} ${dim('ou')} ${cyan(ctx.cwd + '/.claude/agents/<nome>.md')}`);
      return;
    }
    const { showFuzzyPicker, askTuiOrReadline } = require('../tui/bridge');
    const picked = await showFuzzyPicker({
      items: agents,
      getLabel: (a: any) => a.name,
      getDetail: (a: any) => a.description,
      title: 'Select custom agent',
      placeholder: 'Filter by name or description',
    });
    if (!picked) { console.log(`  ${dim('Cancelado.')}`); return; }
    agentName = (picked as any).name;
    task = await askTuiOrReadline(`Task para ${agentName}`);
    if (!task.trim()) { console.log(`  ${dim('Cancelado (task vazia).')}`); return; }
  }
  const { findCustomAgent } = require('../ai/custom-agents');
  const agent = findCustomAgent(ctx.cwd, agentName);
  if (!agent) {
    console.log(`  ${yellow('!')} Custom agent "${agentName}" não encontrado.`);
    console.log(`  ${dim('Execute')} ${cyan('/agents')} ${dim('para ver os disponíveis.')}`);
    return;
  }
  if (!task) {
    console.log(`  ${yellow('!')} Faltou a task. Uso: ${cyan('/agent ' + agentName + ' <descrição da task>')}`);
    return;
  }
  // Dispatch directly via executeTool('dispatch_agent') — reuses all
  // the subagent runtime (tool whitelist, iteration limit, etc.) and
  // gives us streaming output to the TUI message list.
  console.log(`  ${dim('Invocando')} ${cyan(agent.name)} ${dim('...')}`);
  try {
    const { executeTool } = require('../ai/tools');
    const result = await executeTool('dispatch_agent', {
      subagent_type: agent.name,
      task,
    }, ctx);
    try {
      const parsed = JSON.parse(result);
      if (parsed.summary) {
        console.log();
        const { renderMarkdown, looksLikeMarkdown } = require('../markdown');
        const out = looksLikeMarkdown(parsed.summary) ? renderMarkdown(parsed.summary) : parsed.summary;
        console.log(out);
      } else {
        console.log(result);
      }
    } catch {
      console.log(result);
    }
  } catch (err: any) {
    console.log(`  ${yellow('!')} Falha: ${err.message || err}`);
  }
}

async function handleSlashOutputStyle81(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const current = loadSettings().outputStyle || 'default';
  const style = rest[0];
  const valid = ['default', 'terse', 'verbose', 'explain', 'code-only'];
  if (!style || !valid.includes(style)) {
    console.log(`  ${dim('Estilo atual:')} ${cyan(current)}`);
    console.log(dim('  Opções:'));
    console.log(`    ${cyan('default')}    neutro (atual)`);
    console.log(`    ${cyan('terse')}      máx 3 frases, só código, sem preâmbulo/summary`);
    console.log(`    ${cyan('verbose')}    explica cada passo, trade-offs, alternativas`);
    console.log(`    ${cyan('explain')}    didático — narra o que cada bloco faz`);
    console.log(`    ${cyan('code-only')}  só blocos de código, sem prosa`);
    console.log(`  ${dim('Uso:')} /output-style <estilo>`);
    return;
  }
  const settings = loadSettings();
  settings.outputStyle = style as any;
  saveSettings(settings);
  console.log(`  ${green('✓')} Output style: ${cyan(style)}`);
}

async function handleSlashPermissionMode(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const current = loadSettings().permissionMode || 'default';
  const mode = rest[0];
  const valid = ['default', 'plan', 'acceptEdits', 'bypassPermissions', 'dontAsk'];
  if (!mode || !valid.includes(mode)) {
    console.log(`  ${dim('Modo atual:')} ${cyan(current)}`);
    console.log(dim('  Opções:'));
    console.log(`    ${cyan('default')}              regras + policy padrão`);
    console.log(`    ${cyan('plan')}                 bloqueia Write/Edit/MultiEdit`);
    console.log(`    ${cyan('acceptEdits')}          auto-approve Edit-family, Bash ainda pergunta`);
    console.log(`    ${cyan('bypassPermissions')}    auto-allow tudo (deny rules ainda valem)`);
    console.log(`    ${cyan('dontAsk')}              ask vira allow, deny continua deny`);
    console.log(`  ${dim('Uso:')} /permission-mode <modo>`);
    return;
  }
  const settings = loadSettings();
  settings.permissionMode = mode as any;
  saveSettings(settings);
  console.log(`  ${green('✓')} Permission mode: ${cyan(mode)}`);
}

async function handleSlashSchedule(sc: SlashContext): Promise<void> {
  const { argsStr, rest, command, cmd } = sc;
  const sub = rest[0]?.toLowerCase();
  if (!sub || sub === 'list') {
    const schedules = loadSchedules();
    if (schedules.length === 0) {
      console.log();
      console.log(`  ${dim('Nenhum agendamento. Crie com:')}`);
      console.log(`  ${cyan('/schedule add <nome> "<cron>" <comando>')}`);
      console.log(`  ${dim('Exemplo:')} ${cyan('/schedule add nightly-audit "0 2 * * *" /analyze --audit')}`);
      console.log();
    } else {
      console.log();
      console.log(`  ${chalk.white.bold('Agendamentos')}`);
      console.log();
      for (const s of schedules) {
        const status = s.enabled ? green('✓') : dim('✗');
        const next = s.nextRunAt ? new Date(s.nextRunAt).toLocaleString('pt-BR') : '—';
        console.log(`  ${status} ${cyan(s.name)} ${dim(`[${s.cron}]`)}`);
        console.log(`    ${dim('cmd:')}  ${s.command}`);
        console.log(`    ${dim('next:')} ${next}`);
        if (s.lastRunAt) console.log(`    ${dim('last:')} ${new Date(s.lastRunAt).toLocaleString('pt-BR')}`);
      }
      console.log();
    }
  } else if (sub === 'add' && rest.length >= 4) {
    const name = rest[1];
    // Extract quoted cron
    const match = argsStr.match(/^add\s+\S+\s+"([^"]+)"\s+(.+)$/) || argsStr.match(/^add\s+\S+\s+'([^']+)'\s+(.+)$/);
    if (!match) {
      console.log(`  ${yellow('!')} Uso: ${cyan('/schedule add <nome> "<cron>" <comando>')}`);
      return;
    }
    const cron = match[1];
    const command = match[2];
    const sched = addSchedule(name, cron, command);
    const next = sched.nextRunAt ? new Date(sched.nextRunAt).toLocaleString('pt-BR') : '—';
    console.log(`  ${green('✓')} Agendamento ${cyan(name)} criado. Proxima execucao: ${next}`);
  } else if (sub === 'remove' && rest[1]) {
    const ok = removeSchedule(rest[1]);
    console.log(ok ? `  ${green('✓')} Removido` : `  ${yellow('!')} Nao encontrado`);
  } else if ((sub === 'enable' || sub === 'disable') && rest[1]) {
    const ok = toggleSchedule(rest[1], sub === 'enable');
    console.log(ok ? `  ${green('✓')} ${sub === 'enable' ? 'Habilitado' : 'Desabilitado'}` : `  ${yellow('!')} Nao encontrado`);
  } else if (sub === 'daemon') {
    const action = rest[1]?.toLowerCase();
    const { installDaemon, uninstallDaemon, daemonStatus } = require('../daemon');
    if (action === 'install') {
      const r = installDaemon();
      console.log(r.ok ? `  ${green('✓')} ${r.message}` : `  ${yellow('!')} ${r.message}`);
    } else if (action === 'uninstall' || action === 'remove') {
      const r = uninstallDaemon();
      console.log(r.ok ? `  ${green('✓')} ${r.message}` : `  ${yellow('!')} ${r.message}`);
    } else {
      const s = daemonStatus();
      console.log(`  ${dim('Status:')} ${s.installed ? (s.running ? green('ativo') : yellow('parado')) : dim('nao instalado')}`);
      console.log(`  ${dim(s.message)}`);
      console.log();
      console.log(`  ${dim('Uso:')} ${cyan('/schedule daemon install|uninstall|status')}`);
      console.log(`  ${dim('Daemon roda')} ${cyan('makestudio scheduled-run')} ${dim('a cada 60s via launchd/systemd.')}`);
    }
  } else if (sub === 'next' && rest[1]) {
    try {
      const next = computeNextRun(rest.slice(1).join(' '));
      console.log(`  ${dim('Proxima execucao:')} ${cyan(new Date(next).toLocaleString('pt-BR'))}`);
    } catch {
      console.log(`  ${yellow('!')} Cron invalido`);
    }
  } else {
    console.log(`  ${dim('Uso:')}`);
    console.log(`    ${cyan('/schedule list')}`);
    console.log(`    ${cyan('/schedule add <nome> "<cron>" <comando>')}`);
    console.log(`    ${cyan('/schedule remove <nome>')}`);
    console.log(`    ${cyan('/schedule enable|disable <nome>')}`);
    console.log(`    ${cyan('/schedule next "<cron>"')}`);
  }
}

async function handleSlashSkills(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  const skills = loadAllSkills(ctx.cwd);
  if (skills.length === 0) {
    console.log();
    console.log(`  ${dim('Nenhuma skill encontrada.')}`);
    console.log(`  ${dim('Crie skills em')} ${cyan('~/.makestudio/skills/')} ${dim('ou')} ${cyan('.makestudio/skills/')}`);
    console.log(`  ${dim('Formato: arquivo .md com YAML frontmatter.')}`);
    console.log();
  } else {
    console.log();
    console.log(`  ${chalk.white.bold('Skills disponiveis')}`);
    console.log();
    for (const s of skills) {
      const src = s.source === 'project' ? dim('[project]') : dim('[user]');
      console.log(`  ${cyan('/' + s.name)} ${src} ${dim('—')} ${s.description}`);
    }
    console.log();
    console.log(`  ${dim('Execute com')} ${cyan('/<nome>')} ${dim('ou')} ${cyan('/<nome> arg1 arg2')}`);
    console.log();
  }
}


export const AGENT_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/plan'], handler: handleSlashPlan },
  { names: ['/coordinator'], handler: handleSlashCoordinator },
  { names: ['/output-style'], handler: handleSlashOutputStyle },
  { names: ['/memory', '/mem'], handler: handleSlashMemory },
  { names: ['/mcp'], handler: handleSlashMcp },
  { names: ['/agents'], handler: handleSlashAgents },
  { names: ['/agent'], handler: handleSlashAgent },
  { names: ['/output-style', '/ostyle'], handler: handleSlashOutputStyle81 },
  { names: ['/permission-mode', '/pmode'], handler: handleSlashPermissionMode },
  { names: ['/schedule'], handler: handleSlashSchedule },
  { names: ['/skills'], handler: handleSlashSkills },
];
