import { swallow } from '../../utils/log';
/**
 * Slash command handlers — cluster topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `CLUSTER_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';
// Side-effect import: auto-sync registers its discovery hooks at module
// load time. Without this, nothing else statically imports auto-sync (the
// only previous importer was discovery.ts, removed to break the cycle), so
// /cluster enable would no longer trigger the memory sync.
import '../cluster/auto-sync';



async function handleSlashCluster(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { loadClusterConfig, saveClusterConfig } = require('../cluster/config');
  const { startDiscovery, stopDiscovery, listPeers, isDiscoveryRunning } = require('../cluster/discovery');
  const { startClusterServer, stopClusterServer } = require('../cluster/server');
  const sub = (rest[0] || 'list').toLowerCase();
  const cfg = loadClusterConfig();

  if (sub === 'enable' || sub === 'on') {
    if (cfg.enabled && isDiscoveryRunning()) {
      console.log(`[cluster] already enabled (peerId: ${cfg.peerId})`);
      return;
    }
    cfg.enabled = true;
    saveClusterConfig(cfg);
    try {
      await startDiscovery();
      // Bring the WS server up too — without it the LAN-scan discovery
      // path is useless because remote peers can probe our IP but have
      // nothing to connect to on the cluster port. Before this fix the
      // TUI startup hook was the only path that called startClusterServer,
      // so `/cluster enable` after a fresh `enabled: false` boot left
      // the server dead.
      await startClusterServer();
      console.log(`[cluster] enabled — advertising as ${cfg.peerId} on ${cfg.multicastGroup}:${cfg.multicastPort} (ws on :${cfg.listenPort})`);
    } catch (err: any) {
      console.log(`[cluster] failed to start: ${err.message || err}`);
    }
    return;
  }

  if (sub === 'disable' || sub === 'off') {
    cfg.enabled = false;
    saveClusterConfig(cfg);
    stopDiscovery();
    stopClusterServer();
    console.log(`[cluster] disabled`);
    return;
  }

  if (sub === 'info' || sub === 'self') {
    // Render a single framed table instead of five prefixed lines so the
    // output reads as a block rather than spam. Box-drawing characters
    // (┌─┐ │ └─┘) work in any UTF-8 terminal. Width is derived from the
    // longest row so the right border aligns regardless of IP/port length.
    const rows: Array<[string, string]> = [
      ['peerId', cfg.peerId],
      ['enabled', String(cfg.enabled)],
      ['multicast', `${cfg.multicastGroup}:${cfg.multicastPort}`],
      ['ws port', String(cfg.listenPort)],
      ['discovery', isDiscoveryRunning() ? 'running' : 'stopped'],
    ];
    try {
      const { getSwimStats } = require('../cluster/swim');
      const s = getSwimStats?.();
      if (s) {
        rows.push([
          'swim',
          `probes=${s.directProbesSent} acks=${s.directAcksReceived} ` +
          `indirect=${s.indirectProbesSent}/${s.indirectAcksReceived} ` +
          `gossip=${s.gossipApplied} faulty=${s.markedFaulty}`,
        ]);
      }
    } catch (err) { swallow(err); }
    const LABEL_W = Math.max(...rows.map(([k]) => k.length));
    const VALUE_W = Math.max(...rows.map(([, v]) => v.length));
    const INNER = LABEL_W + 3 + VALUE_W;              // label + " : " + value
    const hLine = '─'.repeat(INNER + 2);
    const lines: string[] = [];
    lines.push(`┌${hLine}┐`);
    lines.push(`│ ${'cluster'.padEnd(INNER)} │`);
    lines.push(`├${hLine}┤`);
    for (const [k, v] of rows) {
      lines.push(`│ ${k.padEnd(LABEL_W)} : ${v.padEnd(VALUE_W)} │`);
    }
    lines.push(`└${hLine}┘`);
    // Send as ONE message so MessageList's per-item marginTop doesn't
    // inject blank lines between every row of the table. The TUI
    // bridge's info renderer preserves embedded newlines via Ink's
    // <Text>; console.log fallback joins with \n naturally.
    const block = lines.join('\n');
    try {
      const { getTuiBridge } = require('../tui/bridge');
      const bridge = getTuiBridge?.();
      if (bridge?.addMessage) {
        bridge.addMessage({ role: 'info', text: block });
      } else {
        console.log(block);
      }
    } catch { console.log(block); }
    return;
  }

  if (sub === 'list' || sub === 'peers') {
    if (!cfg.enabled) {
      console.log(`[cluster] disabled. Run /cluster enable to start advertising and discovering peers.`);
      return;
    }
    const peers = listPeers();
    if (peers.length === 0) {
      console.log(`[cluster] no peers discovered yet (beacon every 5s, SWIM probe every 1.5s)`);
      return;
    }
    const stateColor = (s: string): string => {
      if (s === 'alive') return green(s);
      if (s === 'suspect') return yellow(s);
      return red(s);
    };
    console.log(`[cluster] ${peers.length} peer(s):`);
    for (const p of peers) {
      const ageSec = Math.round((Date.now() - p.lastSeen) / 1000);
      console.log(`  ${p.peerId}  ${stateColor(p.state)}  ${p.hostname}@${p.address}:${p.wsPort}  v${p.version}  caps=[${p.caps.join(',')}]  beacon ${ageSec}s ago`);
    }
    return;
  }

  if (sub === 'trust') {
    // /cluster trust                                  → list trusted peers
    // /cluster trust <peer-id> --allow-bash           → grant globally
    // /cluster trust <peer-id> --scope <path> --allow-bash → grant for path
    // /cluster trust <peer-id> --revoke               → revoke all
    // /cluster trust <peer-id> --scope <path> --revoke → revoke that scope
    const { getPeerTrust, setPeerTrust, revokePeerTrust, listPeerTrust } = require('../cluster/trust');
    const targetPeer = rest[1];
    const flags = rest.slice(2);

    // Extract --scope <path> out of the flag stream before parsing capabilities.
    let scope: string | undefined;
    const scopeIdx = flags.indexOf('--scope');
    if (scopeIdx >= 0) {
      scope = flags[scopeIdx + 1];
      if (!scope || scope.startsWith('--')) {
        console.log(`[cluster] --scope requires a path argument`);
        return;
      }
    }

    if (!targetPeer) {
      const trusted = listPeerTrust();
      if (trusted.length === 0) {
        console.log(`[cluster] no peers trusted. Grant with: /cluster trust <peer-id> --allow-bash`);
        return;
      }
      console.log(`[cluster] trusted peers:`);
      for (const t of trusted) {
        const pubkeyHint = t.pubkey ? ` ${dim(`(${t.pubkey.slice(0, 16)}…)`)}` : '';
        console.log(`  ${t.peerId}${pubkeyHint}`);
        console.log(`    global: bash=${t.global.allowBash ? 'yes' : 'no'} write=${t.global.allowWrite ? 'yes' : 'no'}`);
        for (const s of t.scopes) {
          console.log(`    scope ${s.path}: bash=${s.allowBash ? 'yes' : 'no'} write=${s.allowWrite ? 'yes' : 'no'}`);
        }
      }
      return;
    }

    if (flags.includes('--revoke')) {
      const removed = revokePeerTrust(targetPeer, scope);
      const where = scope ? `scope ${scope} of ${targetPeer}` : targetPeer;
      console.log(removed
        ? `[cluster] trust revoked for ${where}`
        : `[cluster] ${where} was not trusted`);
      return;
    }

    const update: any = {};
    if (flags.includes('--allow-bash')) update.allowBash = true;
    if (flags.includes('--deny-bash')) update.allowBash = false;
    if (flags.includes('--allow-write')) update.allowWrite = true;
    if (flags.includes('--deny-write')) update.allowWrite = false;

    if (Object.keys(update).length === 0) {
      const current = getPeerTrust(targetPeer, scope);
      const where = scope ? `${targetPeer} @ ${scope}` : targetPeer;
      console.log(`[cluster] ${where}: bash=${current.allowBash} write=${current.allowWrite}`);
      console.log(`  Flags: --scope <path> --allow-bash --deny-bash --allow-write --deny-write --revoke`);
      return;
    }

    // Pin the pubkey from the discovery registry on first grant. Peers we
    // haven't seen (e.g. offline laptop) can still be pre-trusted — pubkey
    // will be pinned the first time they appear.
    let pubkey: string | undefined;
    try {
      const { listPeers } = require('../cluster/discovery');
      pubkey = listPeers().find((p: any) => p.peerId === targetPeer)?.pubkey;
    } catch (err) { swallow(err); }

    const updated = setPeerTrust(targetPeer, { trust: update, scope, pubkey });
    const where = scope ? `${targetPeer} @ ${scope}` : targetPeer;
    console.log(`[cluster] ${where}: bash=${updated.allowBash} write=${updated.allowWrite}`);
    return;
  }

  if (sub === 'port') {
    // /cluster port <number> — change multicast port (when 42424 is
    // taken by something like OrbStack or docker). Must match on ALL
    // peers in the cluster — the whole point of multicast is that
    // everyone listens on the same group+port.
    const n = Number(rest[1]);
    if (!Number.isInteger(n) || n < 1024 || n > 65535) {
      console.log(`[cluster] Usage: /cluster port <1024-65535>  (current multicast port: ${cfg.multicastPort})`);
      return;
    }
    cfg.multicastPort = n;
    saveClusterConfig(cfg);
    console.log(`[cluster] multicast port set to ${n}. Restarting discovery...`);
    try {
      stopDiscovery();
      if (cfg.enabled) await startDiscovery();
      console.log(`[cluster] discovery restarted. Remember to set the SAME port on every peer.`);
    } catch (err: any) {
      console.log(`[cluster] restart failed: ${err.message || err}`);
    }
    return;
  }

  if (sub === 'debug') {
    // Diagnostic dump — "nobody in /cluster list" split into its
    // possible causes (nothing arrived / arrived but rejected / accepted
    // but dropped from the registry).
    try {
      const { getDiscoveryStats } = require('../cluster/discovery');
      const s = getDiscoveryStats?.();
      const osMod = require('os');
      // Collect all LAN-local IPv4 addresses so the user can tell at a
      // glance which interface the multicast should be going over — if
      // two peers are on different subnets the table makes it obvious.
      const ifaces = osMod.networkInterfaces() as Record<string, any[]>;
      const addrs: string[] = [];
      for (const name of Object.keys(ifaces)) {
        for (const a of ifaces[name] || []) {
          if (a.family === 'IPv4' && !a.internal) addrs.push(`${a.address} (${name})`);
        }
      }
      const lines: string[] = [];
      const joined = (s?.membershipsJoined || []) as string[];
      const failed = (s?.membershipsFailed || []) as Array<{ iface: string; error: string }>;
      const portAttempts = (s?.portAttempts || []) as Array<{ port: number; ok: boolean; error?: string }>;
      const portSummary = portAttempts
        .map((a) => a.ok ? `✓${a.port}` : `✗${a.port} (${(a.error || '').split('\n')[0].slice(0, 40)})`)
        .join(', ');
      const rows: Array<[string, string]> = [
        ['hostname', osMod.hostname()],
        ['addresses', addrs.join(', ') || '<none>'],
        ['listening port', s?.listeningOnPort != null ? String(s.listeningOnPort) : '<not bound>'],
        ['port attempts', portSummary || '<none>'],
        ['multicast joined on', joined.length ? joined.join(', ') : '<none — discovery deaf>'],
        ['multicast join failed', failed.length ? failed.map((f) => `${f.iface}: ${f.error}`).join('; ') : '<none>'],
        ['bind error', s?.bindError || '<none>'],
        ['packets received', String(s?.packetsReceived ?? 0)],
        ['packets parsed', String(s?.packetsParsed ?? 0)],
        ['rejected: not-json', String(s?.rejectedNotJson ?? 0)],
        ['rejected: wrong-type', String(s?.rejectedWrongType ?? 0)],
        ['rejected: no-envelope', String(s?.rejectedNoEnvelope ?? 0)],
        ['rejected: missing fields', String(s?.rejectedMissingFields ?? 0)],
        ['rejected: self-echo', String(s?.rejectedSelfEcho ?? 0)],
        ['rejected: bad fingerprint', String(s?.rejectedBadFingerprint ?? 0)],
        ['rejected: bad signature', String(s?.rejectedBadSignature ?? 0)],
        ['rejected: pubkey mismatch', String(s?.rejectedPubkeyMismatch ?? 0)],
        ['peers accepted (all-time)', String(s?.peersAccepted ?? 0)],
        ['last rejection', s?.lastRejection
          ? `${s.lastRejection.reason} from ${s.lastRejection.from} (${Math.round((Date.now() - s.lastRejection.at) / 1000)}s ago)`
          : 'never'],
        ['last accepted', s?.lastAccepted
          ? `${s.lastAccepted.peerId} from ${s.lastAccepted.from} (${Math.round((Date.now() - s.lastAccepted.at) / 1000)}s ago)`
          : 'never'],
      ];
      // Surface whether the WS server (TCP listener on listenPort) is
      // actually up. Without this the /cluster debug block looked healthy
      // even when peers couldn't reach us because the TCP server had
      // silently failed to bind (see `boot failed` logged to stderr).
      try {
        const { isClusterServerRunning } = require('../cluster/server');
        rows.push(['ws server running', isClusterServerRunning?.() ? 'yes' : 'NO — peers cannot connect']);
      } catch (err) { swallow(err); }
      // LAN-scan (unicast discovery) telemetry — multicast's frequent
      // silent fail means the scanner usually carries the load.
      try {
        const { getScannerStats } = require('../cluster/lan-scanner');
        const scan = getScannerStats?.();
        if (scan) {
          rows.push(['scanner running', scan.running ? 'yes' : 'no']);
          if (scan.lastScan) {
            rows.push(['scanner source', scan.lastScan.source]);
            rows.push(['scanner probed', String(scan.lastScan.probed)]);
            rows.push(['scanner hits', scan.lastScan.accepted.length
              ? `${scan.lastScan.accepted.length} (${scan.lastScan.accepted.join(', ')})`
              : '0']);
            rows.push(['scanner last duration', `${scan.lastScan.durationMs}ms`]);
          } else {
            rows.push(['scanner last scan', 'never (not yet completed)']);
          }
        }
      } catch (err) { swallow(err); }
      const LABEL_W = Math.max(...rows.map(([k]) => k.length));
      const VALUE_W = Math.max(...rows.map(([, v]) => v.length));
      const INNER = LABEL_W + 3 + VALUE_W;
      const hLine = '─'.repeat(INNER + 2);
      lines.push(`┌${hLine}┐`);
      lines.push(`│ ${'cluster debug'.padEnd(INNER)} │`);
      lines.push(`├${hLine}┤`);
      for (const [k, v] of rows) lines.push(`│ ${k.padEnd(LABEL_W)} : ${v.padEnd(VALUE_W)} │`);
      lines.push(`└${hLine}┘`);
      const block = lines.join('\n');
      try {
        const { getTuiBridge } = require('../tui/bridge');
        const bridge = getTuiBridge?.();
        if (bridge?.addMessage) bridge.addMessage({ role: 'info', text: block });
        else console.log(block);
      } catch { console.log(block); }
    } catch (err: any) {
      console.log(`[cluster] debug failed: ${err.message || err}`);
    }
    return;
  }

  console.log(`[cluster] Usage: /cluster [list | enable | disable | info | debug | port <n> | trust [<peer-id> [--scope <path>] --allow-bash|--deny-bash|--allow-write|--deny-write|--revoke]]`);
}


export const CLUSTER_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/cluster'], handler: handleSlashCluster },
];
