import { swallow } from '../../utils/log';
/**
 * Slash command handlers — model topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `MODEL_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashUsage(sc: SlashContext): Promise<void> {
  // Opens the UsageView dashboard (cards + heatmap + model breakdown).
  // App.tsx subscribes to this flag via bridge.onUsageOpenChange and
  // replaces the InputBox with the UsageView until the user presses ESC.
  try {
    const { setUsageOpen } = require('../tui/bridge');
    setUsageOpen(true);
  } catch (err: any) {
    console.log(`[usage] failed to open dashboard: ${err.message || err}`);
  }
}

async function handleSlashStats(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const duration = Math.round((Date.now() - ctx.usage.sessionStartedAt) / 1000);
  const mins = Math.floor(duration / 60);
  const secs = duration % 60;
  const total = ctx.usage.totalTokens || 1;
  const cacheRate = ctx.usage.cacheReads / Math.max(1, ctx.usage.promptTokens);
  // Bundle the report into ONE console.log — TUI router emits each call
  // as a separate <Box> with marginTop:1, which leaves a blank line
  // between every row otherwise. <Text> renders embedded \n correctly.
  const lines: string[] = [];
  lines.push(`  ${bold('Usage stats')} ${dim('(current session)')}`);
  lines.push(`  ${dim('duration:')}       ${mins}m${String(secs).padStart(2, '0')}s`);
  lines.push(`  ${dim('requests:')}       ${ctx.usage.requestCount}`);
  lines.push(`  ${dim('prompt tokens:')}  ${ctx.usage.promptTokens.toLocaleString()}  ${dim(`(${((ctx.usage.promptTokens / total) * 100).toFixed(1)}%)`)}`);
  lines.push(`  ${dim('output tokens:')}  ${ctx.usage.completionTokens.toLocaleString()}  ${dim(`(${((ctx.usage.completionTokens / total) * 100).toFixed(1)}%)`)}`);
  lines.push(`  ${dim('total tokens:')}   ${ctx.usage.totalTokens.toLocaleString()}`);
  lines.push(`  ${dim('cache reads:')}    ${ctx.usage.cacheReads.toLocaleString()}  ${dim(`(${(cacheRate * 100).toFixed(1)}% of prompt)`)}`);
  lines.push(`  ${dim('cache writes:')}   ${ctx.usage.cacheWrites.toLocaleString()}`);
  lines.push(`  ${dim('avg per req:')}    ${Math.round(ctx.usage.totalTokens / Math.max(1, ctx.usage.requestCount)).toLocaleString()} tokens`);

  // Origin breakdown — shows which slice of the spend came from main user
  // turns vs background subagents vs auto-compact / image pipeline. Helps
  // spot runaway fan-outs that wouldn't be visible in the rolled-up totals.
  const origins: any = (ctx.usage as any).byOrigin || {};
  const entries: Array<[string, any]> = Object.entries(origins).filter(([, v]) => v && (v as any).totalTokens > 0);
  if (entries.length > 0) {
    lines.push('');
    lines.push(`  ${bold('by origin')}`);
    const labelW = Math.max(...entries.map(([k]) => k.length)) + 2;
    for (const [origin, v] of entries) {
      const pct = ((v.totalTokens / total) * 100).toFixed(1);
      const label = (origin + ':').padEnd(labelW);
      lines.push(
        `  ${dim(label)}` +
        ` ${v.totalTokens.toLocaleString().padStart(12)} tokens` +
        ` ${dim(`(${pct}%)`)}` +
        ` ${dim('·')} ${v.requestCount} req` +
        ` ${dim('·')} ${dim(`prompt ${v.promptTokens.toLocaleString()}`)} ${dim(`/ out ${v.completionTokens.toLocaleString()}`)}`
      );
    }
  }
  if (ctx.lastToolCall) {
    lines.push(`  ${dim('last tool:')}     ${ctx.lastToolCall.name} ${dim(`(${ctx.lastToolCall.durationMs}ms)`)}`);
  }
  console.log(lines.join('\n'));

  // Tool-call aggregate from ~/.makestudio/events.jsonl (Fase 5.2/5.3).
  // Spans past sessions too — useful to see cross-session patterns
  // (e.g. "Bash always slow", "Read has high fail rate").
  try {
    const { readRecentEvents, eventsFilePath } = require('../../utils/events');
    const limitArg = rest[0] ? parseInt(rest[0], 10) : NaN;
    const limit = Number.isFinite(limitArg) && limitArg > 0 ? limitArg : 2000;
    const events = readRecentEvents(limit);
    const toolCalls = events.filter((e: any) => e.type === 'tool_call');
    if (toolCalls.length === 0) {
      console.log();
      console.log(`  ${dim('(no tool_call events recorded yet — run some tools to populate ' + eventsFilePath() + ')')}`);
      return;
    }

    // Split main-agent calls from subagent-internal calls. Without this,
    // a single dispatch_agent looks cheap (1 call) even though its sub-
    // invocation fired 20 Read/Glob/Grep under the hood.
    const mainCalls = toolCalls.filter((e: any) => e.source !== 'subagent');
    const subCalls = toolCalls.filter((e: any) => e.source === 'subagent');

    // Percentile helper — sorts in place, returns p in [0,1] (e.g. 0.5
    // = median, 0.95 = p95). Empty input returns 0; fewer than 2 entries
    // returns the only value. Avoids a stats lib dependency.
    const pct = (sorted: number[], p: number) => {
      if (sorted.length === 0) return 0;
      const idx = Math.min(sorted.length - 1, Math.floor(sorted.length * p));
      return sorted[idx];
    };

    const aggregate = (events: any[], label: string) => {
      if (events.length === 0) return;
      // Per-tool: counters AND raw duration list so we can compute
      // p50/p95 (avg alone hides tail-latency outliers — e.g. Bash with
      // a 60s timeout makes avg useless if 99% of calls finish in 50ms).
      const byTool: Record<string, { ok: number; fail: number; totalMs: number; durations: number[] }> = {};
      let totalOk = 0, totalFail = 0, totalBlocked = 0, sumMs = 0;
      for (const e of events) {
        const t = (e.tool as string) || 'unknown';
        const slot = byTool[t] || (byTool[t] = { ok: 0, fail: 0, totalMs: 0, durations: [] });
        if (e.ok) { slot.ok++; totalOk++; } else { slot.fail++; totalFail++; }
        if (e.blocked) totalBlocked++;
        const dur = Number(e.durationMs) || 0;
        slot.totalMs += dur;
        slot.durations.push(dur);
        sumMs += dur;
      }
      const errorRate = events.length > 0 ? (totalFail / events.length) * 100 : 0;
      const avgMs = events.length > 0 ? sumMs / events.length : 0;
      console.log();
      console.log(`  ${bold(label)} ${dim(`(${events.length})`)}`);
      console.log(`  ${dim('ok:')}            ${green(String(totalOk))}`);
      console.log(`  ${dim('failed:')}        ${red(String(totalFail))} ${dim(`(${errorRate.toFixed(1)}%)`)}`);
      if (totalBlocked > 0) console.log(`  ${dim('blocked hook:')}  ${yellow(String(totalBlocked))}`);
      console.log(`  ${dim('avg duration:')}  ${avgMs.toFixed(0)}ms`);
      console.log(dim('  By tool (top 10) — avg / p50 / p95:'));
      const rows = Object.entries(byTool)
        .map(([tool, s]) => {
          const sorted = s.durations.slice().sort((a, b) => a - b);
          return {
            tool,
            total: s.ok + s.fail,
            ok: s.ok,
            fail: s.fail,
            avgMs: (s.ok + s.fail) > 0 ? s.totalMs / (s.ok + s.fail) : 0,
            p50: pct(sorted, 0.5),
            p95: pct(sorted, 0.95),
          };
        })
        .sort((a, b) => b.total - a.total)
        .slice(0, 10);
      for (const r of rows) {
        const name = r.tool.padEnd(22);
        const err = r.fail > 0 ? red(`${r.fail} fail`) : dim('0 fail');
        // Highlight p95 in red when it's a clear outlier vs avg (>3×).
        const p95Color = r.p95 > r.avgMs * 3 && r.p95 > 500 ? red : dim;
        console.log(
          `    ${cyan(name)}  ${String(r.total).padStart(5)} calls  ${err}  ` +
          `${dim(`avg ${r.avgMs.toFixed(0)}ms`)}  ${dim(`p50 ${r.p50}ms`)}  ${p95Color(`p95 ${r.p95}ms`)}`
        );
      }
    };

    aggregate(mainCalls, `Main-agent tool calls`);
    aggregate(subCalls, `Subagent tool calls`);

    // Top fanout turns — which prompts caused the most tool calls? When a
    // single user question explodes into 15+ Read/Glob/Grep/Bash, that's
    // usually the model over-investigating something already on disk.
    // Surface the top 5 so you can see which prompts to refactor or
    // re-anchor with an explicit file reference.
    try {
      const byTurn = new Map<string, { count: number; prompt: string }>();
      for (const e of mainCalls) {
        const seq = (e as any).turnSeq;
        if (!seq) continue;
        const key = `${seq}`;
        const slot = byTurn.get(key) || { count: 0, prompt: (e as any).turnPrompt || '' };
        slot.count++;
        if (!slot.prompt && (e as any).turnPrompt) slot.prompt = (e as any).turnPrompt;
        byTurn.set(key, slot);
      }
      const fanoutRows = Array.from(byTurn.entries())
        .map(([seq, s]) => ({ seq, ...s }))
        .filter((r) => r.count >= 5)
        .sort((a, b) => b.count - a.count)
        .slice(0, 5);
      if (fanoutRows.length > 0) {
        const fanLines: string[] = [];
        fanLines.push('');
        fanLines.push(`  ${bold('Top fanout turns')} ${dim('(≥5 tool calls)')}`);
        for (const r of fanoutRows) {
          const flag = r.count >= 15 ? red(String(r.count).padStart(3)) :
                        r.count >= 10 ? yellow(String(r.count).padStart(3)) :
                                        String(r.count).padStart(3);
          const promptOut = r.prompt ? dim(`"${r.prompt}"`) : dim('(no prompt snippet)');
          fanLines.push(`  ${flag} calls  ${dim('· turn #' + r.seq + ' ·')} ${promptOut}`);
        }
        console.log(fanLines.join('\n'));
      }
    } catch (err) { swallow(err); }

    // Cross-session token totals from token_usage events. Each record
    // is one LLM call; adding them gives lifetime spend across all
    // sessions this install has seen (bounded by 5.2 rotation).
    const tokenEvents = events.filter((e: any) => e.type === 'token_usage');
    if (tokenEvents.length > 0) {
      let totPrompt = 0, totCompletion = 0, totCache = 0, totCacheWrite = 0;
      const byModel: Record<string, { prompt: number; completion: number; cache: number; n: number }> = {};
      for (const e of tokenEvents) {
        totPrompt += Number(e.promptTokens) || 0;
        totCompletion += Number(e.completionTokens) || 0;
        totCache += Number(e.cacheReads) || 0;
        totCacheWrite += Number(e.cacheWrites) || 0;
        const k = `${e.provider || '?'} · ${e.model || '?'}`;
        const slot = byModel[k] || (byModel[k] = { prompt: 0, completion: 0, cache: 0, n: 0 });
        slot.prompt += Number(e.promptTokens) || 0;
        slot.completion += Number(e.completionTokens) || 0;
        slot.cache += Number(e.cacheReads) || 0;
        slot.n++;
      }
      const grandTotal = totPrompt + totCompletion;
      const cacheRate = totPrompt > 0 ? (totCache / totPrompt) * 100 : 0;
      console.log();
      console.log(`  ${bold('Tokens')} ${dim(`(${tokenEvents.length} requests across all sessions)`)}`);
      console.log(`  ${dim('prompt:')}        ${totPrompt.toLocaleString()}`);
      console.log(`  ${dim('completion:')}    ${totCompletion.toLocaleString()}`);
      console.log(`  ${dim('total:')}         ${bold(grandTotal.toLocaleString())}`);
      console.log(`  ${dim('cache reads:')}   ${green(totCache.toLocaleString())} ${dim(`(${cacheRate.toFixed(1)}% of prompt)`)}`);
      if (totCacheWrite > 0) console.log(`  ${dim('cache writes:')}  ${totCacheWrite.toLocaleString()}`);
      console.log();
      console.log(dim('  By model:'));
      const modelRows = Object.entries(byModel)
        .map(([k, s]) => ({ k, ...s, total: s.prompt + s.completion }))
        .sort((a, b) => b.total - a.total)
        .slice(0, 6);
      for (const r of modelRows) {
        console.log(`    ${cyan(r.k.padEnd(44))}  ${String(r.n).padStart(4)} req  ${dim('in/out:')} ${String(r.prompt).padStart(9)}/${String(r.completion).padStart(6)}  ${dim('cache:')} ${green(String(r.cache).padStart(7))}`);
      }
    }
  } catch (err: any) {
    console.log();
    console.log(`  ${dim('(tool call stats unavailable:')} ${err.message || err}${dim(')')}`);
  }
}

/**
 * Pure: render the /version block as a single multi-line string. Kept
 * outside the handler so it's unit-testable without having to mock the
 * network fetches or the TUI bridge.
 */
export interface VersionBlockData {
  agent: { version: string; gitCommit: string | null };
  backend: {
    version: string;
    gitCommit: string | null;
    status: string;
    environment: string;
    uptime: string;
  };
  server: string;
  node: string;
  platform: string;
  build: string;
}

export function formatVersionBlock(data: VersionBlockData): string {
  const LABEL_W = 9;
  const pad = (s: string) => s.padEnd(LABEL_W);
  const agentCommit = data.agent.gitCommit ? dim(` @ ${data.agent.gitCommit}`) : '';
  const backendCommit = data.backend.gitCommit ? dim(` @ ${data.backend.gitCommit}`) : '';
  // Filter each meta piece separately — composing "up —" then comparing to
  // "—" wouldn't match (the prefix sticks). Build the parts list, then
  // wrap in parens only when it's non-empty.
  const metaParts: string[] = [];
  if (data.backend.status && data.backend.status !== '—') metaParts.push(data.backend.status);
  if (data.backend.environment && data.backend.environment !== '—') metaParts.push(data.backend.environment);
  if (data.backend.uptime && data.backend.uptime !== '—') metaParts.push(`up ${data.backend.uptime}`);
  const backendMeta = metaParts.length > 0 ? dim(`(${metaParts.join(' · ')})`) : '';
  const lines = [
    `  ${cyan('┌─')} ${cyan('✦')} ${bold('makestudio')}`,
    `  ${cyan('│')}  ${dim(pad('agent'))} ${cyan('v' + data.agent.version)}${agentCommit}`,
    `  ${cyan('│')}  ${dim(pad('backend'))} ${cyan('v' + data.backend.version)}${backendCommit}  ${backendMeta}`,
    `  ${cyan('│')}  ${dim(pad('server'))} ${data.server}`,
    `  ${cyan('│')}  ${dim(pad('node'))} ${data.node}`,
    `  ${cyan('│')}  ${dim(pad('platform'))} ${data.platform}`,
    `  ${cyan('│')}  ${dim(pad('build'))} ${data.build}`,
    `  ${cyan('└──')}`,
  ];
  return lines.join('\n');
}

async function handleSlashVersion(sc: SlashContext): Promise<void> {
  // Resolve the AGENT's package.json — bundled flat under dist/index.js,
  // so we walk up from __dirname until we find one whose name starts
  // with "@makestudio/agent". The previous `require('../../package.json')`
  // landed on the backend's package.json instead.
  const fs = require('fs');
  const path = require('path');
  let pkg: any = null;
  let dir = __dirname;
  for (let i = 0; i < 6 && dir && dir !== path.dirname(dir); i++) {
    const candidate = path.join(dir, 'package.json');
    try {
      if (fs.existsSync(candidate)) {
        const parsed = JSON.parse(fs.readFileSync(candidate, 'utf8'));
        if (typeof parsed?.name === 'string' && parsed.name.startsWith('@makestudio/agent')) {
          pkg = parsed;
          break;
        }
      }
    } catch (err) { swallow(err); }
    dir = path.dirname(dir);
  }
  const agentVersion = pkg?.version || 'unknown';
  const agentGitCommit = pkg?.gitCommit || null;

  // Fetch backend version + health concurrently. Best-effort — we
  // don't block /version on a network hiccup.
  const { ctx } = sc;
  const baseUrl = (ctx as any).serverUrl || (() => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const { loadConfig } = require('../../config/config');
      return loadConfig()?.serverUrl || 'https://api.zielinski.dev.br';
    } catch { return 'https://api.zielinski.dev.br'; }
  })();
  const fetchJSON = async (url: string): Promise<any | null> => {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 3000);
      const res = await (globalThis as any).fetch(url, { signal: ctrl.signal });
      clearTimeout(t);
      if (!res.ok) return null;
      return await res.json();
    } catch { return null; }
  };
  const [versionResp, healthResp] = await Promise.all([
    fetchJSON(`${baseUrl}/api/v1/health/version`),
    fetchJSON(`${baseUrl}/api/v1/health`),
  ]);
  const apiVersion = versionResp?.fullVersion || versionResp?.version || 'unreachable';
  const apiGitCommit = versionResp?.gitCommit || null;
  const apiEnv = healthResp?.environment || versionResp?.environment || '—';
  const apiStatus = healthResp?.status || (versionResp ? 'ok' : 'unreachable');
  const apiUptime = (() => {
    const u = healthResp?.uptime;
    if (typeof u !== 'number') return '—';
    if (u < 60) return `${Math.round(u)}s`;
    if (u < 3600) return `${Math.round(u / 60)}m`;
    if (u < 86400) return `${(u / 3600).toFixed(1)}h`;
    return `${(u / 86400).toFixed(1)}d`;
  })();

  const platform = `${process.platform}-${process.arch}`;
  // Single console.log of the full block — separate console.log calls
  // were each becoming their own TUI message bubble, leaving a visible
  // blank line between every row. One block = one bubble = no gaps.
  const block = formatVersionBlock({
    agent: { version: agentVersion, gitCommit: agentGitCommit },
    backend: {
      version: apiVersion,
      gitCommit: apiGitCommit,
      status: apiStatus,
      environment: apiEnv,
      uptime: apiUptime,
    },
    server: baseUrl,
    node: process.version,
    platform,
    build: new Date().toISOString().slice(0, 10),
  });
  console.log('\n' + block + '\n');
}

async function handleSlashFast(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const s = loadSettings();
  const next = !s.fastMode;
  saveSettings({ fastMode: next });
  console.log(`  ${green('✓')} Fast mode: ${next ? cyan('ON') : dim('off')}`);
  if (next) {
    ctx.effort = 'low';
    console.log(`  ${dim('(effort lowered to "low"; /model to change the model itself)')}`);
  } else {
    ctx.effort = 'medium';
  }
}

async function handleSlashAi(sc: SlashContext): Promise<void> {
  const { ctx, trimmed } = sc;
  handleProviderSwitch(trimmed, ctx);
}

async function handleSlashEffort(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const level = rest[0]?.toLowerCase();
  const valid = ['low', 'medium', 'high', 'max'];
  if (!level || !valid.includes(level)) {
    console.log(`  ${dim('Nivel atual:')} ${cyan(ctx.effort)}`);
    console.log(`  ${dim('Opcoes:')} ${valid.map(v => cyan(v)).join(', ')}`);
    console.log(`  ${dim('  low:')}    respostas curtas, poucas tool calls, barato`);
    console.log(`  ${dim('  medium:')} balanceado (padrao)`);
    console.log(`  ${dim('  high:')}   detalhado, explora bem, mais tool calls`);
    console.log(`  ${dim('  max:')}    maximo esforco, roda tudo que puder`);
    return;
  }
  ctx.effort = level as any;
  console.log(`  ${green('✓')} Esforco alterado para ${cyan(level)}`);
}

async function handleSlashCost(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  handleCostCommand(ctx);
}

async function handleSlashModel84(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // Lists the API configs registered in the backend (ApiConfigs page)
  // and lets the user pick one to activate. No hardcoded catalogs: if a
  // model isn't registered as a config, it's not shown.
  const { getApiClient } = require('../../network/api-client');
  const api = getApiClient();
  try {
    const activeRes = await api.get('/api-configs/active', { timeout: 8_000 }).catch(() => ({ data: {} }));
    const active = activeRes.data || {};

    // Backend caps limit at 50 — iterate until hasNextPage=false.
    // BUG-FIX: `return` here exited the whole function on the first page
    // (every typical setup has ≤50 configs so hasNextPage is false right
    // away), so /model would print nothing and prompt nothing. Must be
    // `break` so the listing/prompt logic below actually runs.
    const list: any[] = [];
    for (let page = 1; page <= 20; page++) {
      const res = await api.get(`/api-configs?limit=50&page=${page}`, { timeout: 8_000 });
      const batch: any[] = res.data?.data || [];
      list.push(...batch);
      if (!res.data?.hasNextPage || batch.length === 0) break;
    }
    const configs = list.filter((c) => c && c.isActive !== false);

    if (configs.length === 0) {
      console.log(`  ${yellow('!')} Nenhuma configuracao ativa cadastrada em ApiConfigs.`);
      console.log(`  ${dim('Cadastre uma em')} ${cyan('https://www.zielinski.dev.br/api-configs')}`);
      return;
    }

    const quickArg = rest[0]?.trim();

    let target: any = null;
    if (quickArg) {
      target = configs.find((c) =>
        c.id === quickArg ||
        c.name?.toLowerCase() === quickArg.toLowerCase() ||
        c.model?.toLowerCase() === quickArg.toLowerCase(),
      );
      if (!target) {
        console.log(`  ${yellow('!')} Configuracao "${quickArg}" nao encontrada.`);
        return;
      }
    } else {
      console.log(`  ${dim('Ativa:')} ${cyan(active.name || active.model || '?')}  ${dim(`(${active.provider || '?'})`)}`);
      console.log(dim('  Configuracoes cadastradas:'));
      configs.forEach((c, i) => {
        const mark = c.id === active.id ? green('●') : dim('○');
        const provider = c.provider || '?';
        const name = c.name || c.model || c.id;
        const model = c.model || '?';
        console.log(`    ${mark} ${cyan(String(i + 1).padStart(2))}  ${name}  ${dim(`— ${provider} · ${model}`)}`);
      });
      const { askTuiOrReadline } = require('../tui/bridge');
      const pick = await askTuiOrReadline('Escolher config (numero ou nome, Enter=cancelar)');
      if (!pick) {
        console.log(`  ${dim('Cancelado.')}`);
        return;
      }
      const idx = parseInt(pick, 10);
      if (!isNaN(idx) && idx >= 1 && idx <= configs.length) {
        target = configs[idx - 1];
      } else {
        target = configs.find((c) =>
          c.name?.toLowerCase() === pick.toLowerCase() ||
          c.model?.toLowerCase() === pick.toLowerCase(),
        );
      }
      if (!target) {
        console.log(`  ${yellow('!')} Selecao invalida.`);
        return;
      }
    }

    if (target.id === active.id) {
      console.log(`  ${dim('Ja e a ativa:')} ${cyan(target.name || target.model)}.`);
      return;
    }

    // Make `target` the one findActive() picks: isDefault=true + lowest
    // priority. Clear isDefault on siblings so the tie-breaker resolves
    // to `target` unambiguously.
    const peers = configs.filter((c) => c.id !== target.id && c.isDefault);
    await Promise.all(
      peers.map((c) =>
        api.patch(`/api-configs/${c.id}`, { isDefault: false }, { timeout: 8_000 })
          .catch(() => { /* best effort */ }),
      ),
    );
    await api.patch(
      `/api-configs/${target.id}`,
      { isDefault: true, isActive: true, priority: 0 },
      { timeout: 8_000 },
    );
    await ctx.fetchProviderInfo();
    console.log(`  ${green('✓')} Config ativa: ${cyan(target.name || target.model)} ${dim(`(${target.provider} · ${target.model})`)}`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Falha ao mudar config: ${err.response?.data?.message || err.message || err}`);
  }
}

async function handleSlashCtx(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  handleCtxCommand(ctx);
}


export const MODEL_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/usage'], handler: handleSlashUsage },
  { names: ['/stats'], handler: handleSlashStats },
  { names: ['/version'], handler: handleSlashVersion },
  { names: ['/fast'], handler: handleSlashFast },
  { names: ['/ai'], handler: handleSlashAi },
  { names: ['/effort'], handler: handleSlashEffort },
  // The duplicate /model registration at the end of this list used to
  // shadow this one (last write wins), so the tier-based handler was
  // dead code. Drop it; /model now resolves to handleSlashModel84
  // (the ApiConfigs-driven picker) directly.
  { names: ['/cost'], handler: handleSlashCost },
  { names: ['/model'], handler: handleSlashModel84 },
  { names: ['/ctx', '/context'], handler: handleSlashCtx },
];
