/**
 * Slash command handlers — repo topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `REPO_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashPr(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const pre = ghPreflight(ctx.cwd);
  if (!pre.ok) { console.log(`  ${yellow('!')} ${pre.hint}`); return; }
  const ref = rest[0];
  const { execSync } = require('child_process');

  // /pr list / /pr ls — discover PRs (any state)
  if (!ref || ref === 'list' || ref === 'ls') {
    try {
      const stateIdx = rest.indexOf('--state');
      const state = stateIdx >= 0 ? rest[stateIdx + 1] : 'all';
      const out = execSync(
        `gh pr list --state ${state} --limit 30 --json number,title,state,author,updatedAt`,
        { cwd: ctx.cwd, encoding: 'utf8' },
      );
      const prs = JSON.parse(out || '[]');
      if (!prs.length) { console.log(`  ${dim('No PRs matching state=' + state)}`); return; }
      console.log(`  ${bold(`PRs in this repo (${state})`)}`);
      for (const p of prs) {
        const color = p.state === 'OPEN' ? green : p.state === 'MERGED' ? cyan : dim;
        console.log(`  ${color('●')} ${cyan('#' + p.number)}  ${p.title.substring(0, 70)}  ${dim(`(${p.state.toLowerCase()} · ${p.author?.login || '?'})`)}`);
      }
      console.log(`  ${dim('Use /pr <number> to load one into context.')}`);
      return;
    } catch (err: any) {
      console.log(`  ${yellow('!')} ${ghErrorHint(err)}`);
      return;
    }
  }

  try {
    const prNum = ref.match(/\d+/)?.[0] || ref;
    const view = execSync(`gh pr view ${prNum} --json title,body,author,state,url,mergedAt,closedAt`, { cwd: ctx.cwd, encoding: 'utf8' });
    const info = JSON.parse(view);
    const comments = execSync(`gh api repos/{owner}/{repo}/pulls/${prNum}/comments --paginate`, { cwd: ctx.cwd, encoding: 'utf8' });
    const list = JSON.parse(comments || '[]');
    const stateColor = info.state === 'OPEN' ? green : info.state === 'MERGED' ? cyan : dim;
    console.log(`  ${bold('PR #' + prNum)} ${cyan(info.title)} ${stateColor(`(${info.state.toLowerCase()})`)}`);
    console.log(`  ${dim('by:')} ${info.author?.login || '?'}  ${dim('·')} ${info.url}`);
    if (info.mergedAt) console.log(`  ${dim('merged:')} ${info.mergedAt}`);
    else if (info.closedAt) console.log(`  ${dim('closed:')} ${info.closedAt}`);
    console.log(`  ${dim('comments:')} ${list.length}`);
    ctx.messages.push({
      role: 'user',
      content: `Context: GitHub PR #${prNum} "${info.title}" (state: ${info.state}).\n\nBody:\n${info.body || '(empty)'}\n\nReview comments:\n${list.map((c: any) => `- [${c.path}:${c.line || '?'}] ${c.user?.login}: ${c.body}`).join('\n') || '(none)'}`,
    });
    console.log(`  ${green('✓')} PR loaded into context.`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} ${ghErrorHint(err)}`);
  }
}

async function handleSlashAutofixPr(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const pre = ghPreflight(ctx.cwd);
  if (!pre.ok) { console.log(`  ${yellow('!')} ${pre.hint}`); return; }
  const ref = rest[0];
  if (!ref) { console.log(`  ${dim('Usage: /autofix-pr <number>')}`); return; }
  try {
    const { execSync } = require('child_process');
    const prNum = ref.match(/\d+/)?.[0] || ref;
    const comments = execSync(`gh api repos/{owner}/{repo}/pulls/${prNum}/comments --paginate`, { cwd: ctx.cwd, encoding: 'utf8' });
    const list = JSON.parse(comments || '[]');
    if (list.length === 0) { console.log(`  ${dim('No review comments on PR #' + prNum)}`); return; }
    const instructions = list.map((c: any, i: number) =>
      `${i + 1}. ${c.path}:${c.line || '?'} (${c.user?.login}): ${c.body.replace(/\n/g, ' ').substring(0, 300)}`,
    ).join('\n');
    ctx.messages.push({
      role: 'user',
      content: `Address these PR review comments from #${prNum}. For each one, make the requested change using Read/Edit/MultiEdit. Keep a TodoWrite list of items so we can track progress. Do not commit — leave the working tree dirty so the user can review.\n\n${instructions}`,
    });
    console.log(`  ${green('✓')} Loaded ${list.length} PR comment(s). Agent will address them on the next prompt.`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} ${ghErrorHint(err)}`);
  }
}

async function handleSlashIssue(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const pre = ghPreflight(ctx.cwd);
  if (!pre.ok) { console.log(`  ${yellow('!')} ${pre.hint}`); return; }
  const ref = rest[0];
  if (!ref) { console.log(`  ${dim('Usage: /issue <number|url>')}`); return; }
  try {
    const { execSync } = require('child_process');
    const num = ref.match(/\d+/)?.[0] || ref;
    const view = execSync(`gh issue view ${num} --json title,body,author,state,labels,comments,url`, { cwd: ctx.cwd, encoding: 'utf8' });
    const info = JSON.parse(view);
    console.log(`  ${bold('Issue #' + num)} ${cyan(info.title)} ${dim(`(${info.state})`)}`);
    console.log(`  ${dim('by:')} ${info.author?.login || '?'}  ${dim('·')} ${info.url}`);
    if (info.labels?.length) console.log(`  ${dim('labels:')} ${info.labels.map((l: any) => l.name).join(', ')}`);
    ctx.messages.push({
      role: 'user',
      content: `Context: GitHub issue #${num} "${info.title}".\n\nBody:\n${info.body || '(empty)'}\n\nComments:\n${(info.comments || []).map((c: any) => `- ${c.author?.login}: ${c.body}`).join('\n')}`,
    });
    console.log(`  ${green('✓')} Issue loaded into context.`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} ${ghErrorHint(err)}`);
  }
}

async function handleSlashReleaseNotes(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const fromIdx = rest.indexOf('--from');
  const fromTag = fromIdx >= 0 ? rest[fromIdx + 1] : null;
  try {
    const { execSync } = require('child_process');
    let fromRef: string;
    if (fromTag) {
      fromRef = fromTag;
    } else {
      try {
        fromRef = execSync('git describe --tags --abbrev=0', { cwd: ctx.cwd, encoding: 'utf8' }).trim();
      } catch {
        fromRef = 'HEAD~20';
      }
    }
    const log = execSync(`git log --pretty=format:"%h|%s|%an|%ad" --date=short ${fromRef}..HEAD`, { cwd: ctx.cwd, encoding: 'utf8' });
    if (!log.trim()) { console.log(`  ${dim('No commits since')} ${cyan(fromRef)}`); return; }
    const commits = log.split('\n').map((l: string) => {
      const [hash, subject, author, date] = l.split('|');
      return { hash, subject, author, date };
    });
    const byType: Record<string, typeof commits> = {};
    for (const c of commits) {
      const match = c.subject.match(/^(\w+)(?:\(.+?\))?:/);
      const type = match ? match[1] : 'other';
      if (!byType[type]) byType[type] = [];
      byType[type].push(c);
    }
    const labelOf: Record<string, string> = {
      feat: 'Features', fix: 'Bug fixes', perf: 'Performance', refactor: 'Refactors',
      docs: 'Documentation', test: 'Tests', chore: 'Chores', style: 'Style', other: 'Other',
    };
    const out: string[] = [];
    out.push(`# Release notes`);
    out.push(``);
    out.push(`From ${fromRef} to HEAD (${commits.length} commit${commits.length === 1 ? '' : 's'})`);
    out.push(``);
    for (const type of Object.keys(byType).sort((a, b) => {
      const order = ['feat', 'fix', 'perf', 'refactor', 'docs', 'test', 'chore', 'style', 'other'];
      return order.indexOf(a) - order.indexOf(b);
    })) {
      out.push(`## ${labelOf[type] || type}`);
      out.push('');
      for (const c of byType[type]) {
        out.push(`- ${c.subject} (\`${c.hash}\` — ${c.author})`);
      }
      out.push('');
    }
    console.log(out.join('\n'));
  } catch (err: any) {
    console.log(`  ${yellow('!')} Failed: ${err.message?.split('\n')[0]}`);
  }
}

async function handleSlashReview(sc: SlashContext): Promise<void> {
  console.log(`  ${dim('Running security review + code review in parallel...')}`);
  try {
    const { securityReviewCommand } = require('../../commands/security-review');
    await securityReviewCommand({});
  } catch (err: any) {
    console.log(`  ${yellow('!')} Security review failed: ${err.message}`);
  }
}

async function handleSlashInit(sc: SlashContext): Promise<void> {
  const { argsStr } = sc;
  await withDetachedRepl(async () => {
    const { initCommand } = require('../../commands/init');
    const args = parseSlashArgs(argsStr);
    await initCommand({ path: args.path, cli: args.cli });
  });
}

async function handleSlashStart(sc: SlashContext): Promise<void> {
  const { argsStr } = sc;
  await withDetachedRepl(async () => {
    const { startCommand } = require('../../commands/start');
    const args = parseSlashArgs(argsStr);
    await startCommand(args);
  });
}

async function handleSlashDiff(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  handleDiff(ctx, rest);
}

async function handleSlashBranch(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  handleBranch(ctx, rest);
}

async function handleSlashCommit(sc: SlashContext): Promise<void> {
  const { ctx, trimmed } = sc;
  await handleCommit(ctx, trimmed);
}


export const REPO_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/pr', '/pr-comments'], handler: handleSlashPr },
  { names: ['/autofix-pr'], handler: handleSlashAutofixPr },
  { names: ['/issue'], handler: handleSlashIssue },
  { names: ['/release-notes'], handler: handleSlashReleaseNotes },
  { names: ['/review'], handler: handleSlashReview },
  { names: ['/init'], handler: handleSlashInit },
  { names: ['/start'], handler: handleSlashStart },
  { names: ['/diff'], handler: handleSlashDiff },
  { names: ['/branch'], handler: handleSlashBranch },
  { names: ['/commit'], handler: handleSlashCommit },
];
