import { swallow } from '../../utils/log';
/**
 * Slash command handlers — security topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `SECURITY_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashSecurityReview(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  await withDetachedRepl(async () => {
    const { securityReviewCommand } = require('../../commands/security-review');
    await securityReviewCommand({ base: rest[0] });
  });
}

async function handleSlashVerbose(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  // Toggle verbose mode (show/hide tool call cards in the message list).
  const { loadSettings: _ls, saveSettings: _ss } = require('../settings');
  const _sv = _ls();
  const _arg = (rest[0] || '').toLowerCase().trim();
  let _nextVerbose: boolean;
  if (_arg === 'on')       _nextVerbose = true;
  else if (_arg === 'off') _nextVerbose = false;
  else                     _nextVerbose = !(_sv.verbose ?? false);
  _ss({ verbose: _nextVerbose });
  const { tuiLog } = require('../tui/bridge');
  if (_nextVerbose) {
    tuiLog('verbose on — tool call cards visible', 'info');
  } else {
    tuiLog('verbose off — tool names shown in status line only', 'info');
  }
}

async function handleSlashVerify(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  // Toggle the auto-verify subagent that runs after edit turns.
  // Default is OFF — opt in with /verify on.
  // Accepts: /verify, /verify on, /verify off
  const { loadSettings, saveSettings } = require('../settings');
  const s = loadSettings() || {};
  const currentlyEnabled = s.autoVerifyEnabled === true
    || (s.autoVerifyDisabled === false && s.autoVerifyEnabled === undefined);
  const arg = (rest[0] || '').toLowerCase().trim();
  let nextEnabled: boolean;
  if (arg === 'on')       nextEnabled = true;
  else if (arg === 'off') nextEnabled = false;
  else                    nextEnabled = !currentlyEnabled;
  // Write the new field and clear the deprecated one to keep
  // settings.json single-sourced.
  saveSettings({ autoVerifyEnabled: nextEnabled, autoVerifyDisabled: undefined });
  const statusWord = nextEnabled ? cyan('ON') : dim('off');
  console.log(`  ${green('✓')} Auto-verify: ${statusWord}`);
  console.log(`  ${dim('(after any turn with edits, a read-only subagent runs builds/tests/probes and reports PASS/FAIL/PARTIAL. Default off — opt in only when you need the safety net.)')}`);
}

async function handleSlashFeedback(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const message = rest.join(' ').trim();
  if (!message) { console.log(`  ${dim('Usage: /feedback <message>')}`); return; }
  const feedbackFile = path.join(os.homedir(), '.makestudio', 'feedback.log');
  try {
    fs.mkdirSync(path.dirname(feedbackFile), { recursive: true });
    const entry = {
      timestamp: new Date().toISOString(),
      user: ctx.user?.email,
      cwd: ctx.cwd,
      version: (() => { try { return require('../../package.json').version; } catch { return '?'; } })(),
      message,
    };
    fs.appendFileSync(feedbackFile, JSON.stringify(entry) + '\n', 'utf8');
    // Also try to send to backend (best effort)
    try {
      const { getApiClient } = require('../../network/api-client');
      const api = getApiClient();
      await api.post('/feedback', entry, { timeout: 5_000 }).catch(() => { /* */ });
    } catch (err) { swallow(err); }
    console.log(`  ${green('✓')} Feedback recorded (${feedbackFile})`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Failed: ${err.message}`);
  }
}

async function handleSlashLogin(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Use the TUI input box for prompts (askTuiOrReadline routes through
  // pendingQuestion when the bridge is installed). NO withDetachedRepl —
  // unmounting Ink mid-command races with raw-mode reset and made Enter
  // print as ^M. Staying inside the TUI is the simpler + correct path.
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { loginCommand } = require('../../commands/login');
    await loginCommand({});
    await ctx.initialize();
    if ((ctx as any).sessionKeyInjected) {
      const info = (ctx as any).providerInfo;
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const { tuiLog } = require('../tui/bridge');
      tuiLog(`✓ session key injected — direct LLM: ${info?.provider}/${info?.model}`, 'info');
    } else {
      const reason = (ctx as any).sessionKeyError || 'unknown';
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const { tuiLog } = require('../tui/bridge');
      tuiLog(`Session key NOT injected — chat will refuse to start. Reason: ${reason}`, 'warn');
    }
  } catch (err: any) {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { tuiLog } = require('../tui/bridge');
    tuiLog(`Login falhou: ${err?.message || err}`, 'error');
  }
}

async function handleSlashHooks(sc: SlashContext): Promise<void> {
  const { ctx, rest, command, cmd } = sc;
  const sub = rest[0]?.toLowerCase();
  // /hooks status — list async hooks currently in flight (PID, event, command, age).
  if (sub === 'status') {
    const { listAsyncHooks } = require('../hooks');
    const inFlight = listAsyncHooks();
    console.log();
    console.log(`  ${chalk.white.bold('Async hooks em execução')}`);
    console.log();
    if (inFlight.length === 0) {
      console.log(`  ${dim('Nenhum async hook rodando.')}`);
    } else {
      for (const h of inFlight) {
        const ageMs = Date.now() - h.startedAt;
        const age = ageMs < 1000 ? `${ageMs}ms` : `${(ageMs / 1000).toFixed(1)}s`;
        console.log(`  ${cyan(`pid ${h.pid}`)} ${dim(h.event)} ${dim(`(${age})`)}: ${h.command}`);
      }
    }
    console.log();
    return;
  }
  const { loadHooks } = require('../hooks');
  const hooks = loadHooks(ctx.activeProject?.localPath || ctx.cwd);
  console.log();
  console.log(`  ${chalk.white.bold('Hooks configurados')}`);
  console.log();
  const events = Object.keys(hooks);
  if (events.length === 0) {
    console.log(`  ${dim('Nenhum hook. Crie em:')}`);
    console.log(`  ${cyan('~/.makestudio/hooks.json')} ${dim('(global)')}`);
    console.log(`  ${cyan('.makestudio/hooks.json')} ${dim('(projeto)')}`);
    console.log();
    console.log(`  ${dim('Exemplo:')}`);
    console.log(`  ${dim('{ "pre-commit": ["npm run lint"], "post-task": ["fvm dart analyze"] }')}`);
  } else {
    for (const event of events) {
      console.log(`  ${cyan(event)}:`);
      for (const cmd of hooks[event]) console.log(`    ${dim('·')} ${cmd}`);
    }
  }
  console.log();
  console.log(`  ${dim('Use')} ${cyan('/hooks status')} ${dim('para ver async hooks rodando.')}`);
  console.log();
}

async function handleSlashQualityHold(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const { runQualityHoldCommand } = require('../../commands/quality-hold');
  const projectId = ctx.activeProject?.id;
  try {
    await runQualityHoldCommand(rest, { projectId });
  } catch (err: any) {
    console.log();
    console.log(`  ${red('✗')} ${dim(`Quality hold falhou: ${err.message}`)}`);
    console.log();
  }
}

async function handleSlashSandbox(sc: SlashContext): Promise<void> {
  const { detectSandboxBackend } = require('../sandbox');
  const backend = detectSandboxBackend();
  console.log();
  console.log(`  ${chalk.white.bold('Sandbox status')}`);
  console.log();
  console.log(`  ${dim('Platform:')}  ${cyan(process.platform)}`);
  console.log(`  ${dim('Backend:')}   ${backend === 'none' ? yellow(backend) : green(backend)}`);
  if (backend === 'none') {
    if (process.platform === 'linux') {
      console.log(`  ${yellow('!')} bwrap nao instalado. Instale: ${cyan('sudo apt install bubblewrap')} ou ${cyan('brew install bubblewrap')}`);
    } else if (process.platform === 'darwin') {
      console.log(`  ${yellow('!')} sandbox-exec deveria estar disponivel no macOS.`);
    } else {
      console.log(`  ${yellow('!')} Plataforma ${process.platform} nao tem backend de sandbox suportado.`);
    }
  } else {
    console.log(`  ${green('✓')} shell_run usa sandbox automaticamente.`);
    console.log(`  ${dim('Levels:')} readonly (safe cmds) · project (default) · full (opt-in) · none (disabled)`);
  }
  console.log();
}

async function handleSlashPermissions(sc: SlashContext): Promise<void> {
  const { ctx, command, cmd } = sc;
  const { loadPolicy } = require('../permissions');
  const policy = loadPolicy(ctx.activeProject?.localPath || ctx.cwd);
  console.log();
  console.log(`  ${chalk.white.bold('Permissions policy')}`);
  console.log();
  console.log(`  ${dim('Default:')} ${cyan(policy.policy)}`);
  if (policy.rules.length === 0) {
    console.log(`  ${dim('Nenhuma regra definida.')}`);
    console.log();
    console.log(`  ${dim('Crie em')} ${cyan('~/.makestudio/permissions.json')} ${dim('ou')} ${cyan('.makestudio/permissions.json')}`);
    console.log(`  ${dim('Exemplo:')}`);
    console.log(`  ${dim('{ "policy": "ask", "rules": [')}`);
    console.log(`  ${dim('   { "tool": "shell_run", "command": "npm *", "action": "allow" },')}`);
    console.log(`  ${dim('   { "tool": "shell_run", "command": "rm *", "action": "deny"  }')}`);
    console.log(`  ${dim(']}')}`);
  } else {
    console.log(`  ${dim('Rules (order matters, first match wins):')}`);
    for (const r of policy.rules) {
      const parts: string[] = [cyan(r.tool)];
      if (r.command) parts.push(dim('cmd=' + r.command));
      if (r.pathPrefix) parts.push(dim('path=' + r.pathPrefix));
      if (r.domain) parts.push(dim('domain=' + r.domain));
      const color = r.action === 'allow' ? green : r.action === 'deny' ? chalk.hex('#EF4444') : yellow;
      console.log(`    ${color(r.action.padEnd(5))} ${parts.join(' ')}`);
    }
  }
  console.log();
}

async function handleSlashTrust(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const action = rest[0]?.toLowerCase();
  if (action === 'on' || action === 'all') {
    ctx.autoApprove = true;
    console.log(`  ${green('✓')} Modo confiável ATIVADO — IA pode usar tools sensíveis sem confirmação.`);
  } else if (action === 'off') {
    ctx.autoApprove = false;
    ctx.approvedTools.clear();
    console.log(`  ${yellow('!')} Modo confiável DESATIVADO — confirmação será pedida.`);
  } else {
    // Single multi-line console.log — the bridge collapses each console.log
    // into one info bubble; sending three separate calls produced three
    // stacked single-liners with their own info icon. One block = one card.
    const status = ctx.autoApprove ? green('confiável (sem confirmação)') : cyan('pedindo confirmação');
    const approved = [...ctx.approvedTools].join(', ') || dim('(nenhuma)');
    const lines = [
      `  ${bold('/trust')} ${dim('— modo de confiança da sessão')}`,
      `  ${dim('estado:')}    ${status}`,
      `  ${dim('aprovadas:')} ${approved}`,
      `  ${dim('uso:')}       ${cyan('/trust on')}  ${dim('|')}  ${cyan('/trust off')}`,
      `  ${dim('persistente:')} use ${cyan('/permission-mode bypassPermissions')} pra que valha entre sessões`,
    ];
    console.log(lines.join('\n'));
  }
}

async function handleSlashDebug(sc: SlashContext): Promise<void> {
  const { ctx, rest, input } = sc;
  const subCmd = rest[0]?.toLowerCase();
  let dbgMod: any = null;
  try { dbgMod = require('../debug-log'); } catch (err) { swallow(err); }

  // /debug log — show audit log path and toggle
  if (subCmd === 'log' || subCmd === 'on' || subCmd === 'off') {
    console.log();
    if (subCmd === 'on') {
      dbgMod?.enableDebugLog();
      const p = dbgMod?.getDebugLogPath();
      console.log(`  ${green('debug log on')}${p ? '  →  ' + dim(p) : ''}`);
    } else if (subCmd === 'off') {
      dbgMod?.disableDebugLog();
      console.log(`  ${dim('debug log off')}`);
    } else {
      const enabled = dbgMod?.isDebugEnabled() ?? false;
      const p = dbgMod?.getDebugLogPath();
      console.log(`  ${dim('Debug log:')} ${enabled ? green('on') : dim('off')}`);
      if (p) console.log(`  ${dim('Log path:')}  ${cyan(p)}`);
      else   console.log(`  ${dim('Start with')} ${cyan('makestudio --debug')} ${dim('or')} ${cyan('/debug on')} ${dim('to activate')}`);
      console.log();
      console.log(`  ${dim('/debug on')}   — ativa log desta sessao`);
      console.log(`  ${dim('/debug off')}  — desativa`);
      console.log(`  ${dim('makestudio --debug')}  — ativa automaticamente`);
      console.log(`  ${dim('DEBUG=1 makestudio')}  — mesmo efeito via env`);
    }
    console.log();
    return;
  }

  // default: show last tool call (original behavior)
  const last = ctx.lastToolCall;
  console.log();
  if (!last) {
    console.log(`  ${dim('Nenhuma tool call nesta sessao ainda.')}`);
    const p = dbgMod?.getDebugLogPath();
    if (p) console.log(`  ${dim('Audit log ativo:')} ${cyan(p)}`);
    else   console.log(`  ${dim('Use')} ${cyan('/debug log')} ${dim('para ver o audit trail completo')}`);
    console.log();
    return;
  }
  console.log(`  ${chalk.white.bold('Ultima Tool Call')}`);
  console.log();
  console.log(`  ${dim('Tool:')}      ${cyan(last.name)}`);
  console.log(`  ${dim('Quando:')}    ${dim(new Date(last.timestamp).toLocaleString('pt-BR'))}`);
  console.log(`  ${dim('Duracao:')}   ${green(last.durationMs + 'ms')}`);
  console.log(`  ${dim('Input:')}`);
  console.log(JSON.stringify(last.input, null, 2).split('\n').map(l => '    ' + l).join('\n'));
  console.log(`  ${dim('Output:')}`);
  const out = last.output.length > 2000 ? last.output.slice(0, 2000) + `\n... [+${last.output.length - 2000} chars]` : last.output;
  console.log(out.split('\n').map(l => '    ' + l).join('\n'));
  const p2 = dbgMod?.getDebugLogPath();
  if (p2) console.log(`\n  ${dim('Audit log completo:')} ${cyan(p2)}`);
  console.log();
}


export const SECURITY_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/security-review', '/secreview'], handler: handleSlashSecurityReview },
  { names: ['/verbose'], handler: handleSlashVerbose },
  { names: ['/verify'], handler: handleSlashVerify },
  { names: ['/feedback'], handler: handleSlashFeedback },
  { names: ['/login'], handler: handleSlashLogin },
  { names: ['/hooks'], handler: handleSlashHooks },
  { names: ['/quality-hold', '/qhold', '/qh'], handler: handleSlashQualityHold },
  { names: ['/sandbox'], handler: handleSlashSandbox },
  { names: ['/permissions', '/perms'], handler: handleSlashPermissions },
  { names: ['/trust'], handler: handleSlashTrust },
  { names: ['/debug'], handler: handleSlashDebug },
];
