import { swallow } from '../../utils/log';
/**
 * Slash command handlers — session topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `SESSION_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashClear(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Full reset: LLM context, visible TUI messages, terminal scrollback.
  ctx.clearConversation();
  // Persist the cleared state — without rewriting the session file, the
  // jsonl still has every message and the next boot reloads them all,
  // so /clear "didn't stick" — same class of bug as /compact had.
  try {
    require('../sessions').rewriteSession(ctx, []);
  } catch (err) { swallow(err); }
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const b = require('../tui/bridge').getTuiBridge?.();
    b?.clearMessages?.();
  } catch (err) { swallow(err); }
  // \x1B[2J clear screen, \x1B[3J clear scrollback, \x1B[H cursor home
  process.stdout.write('\x1B[2J\x1B[3J\x1B[H');
  console.log(`  ${green('*')} Historico limpo.`);
}

async function handleSlashCopy(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  const { copyToClipboard } = require('../clipboard');
  const lastAsst = [...ctx.messages].reverse().find(m => m.role === 'assistant');
  if (!lastAsst) { console.log(`  ${dim('(no assistant response to copy)')}`); return; }
  const text = typeof lastAsst.content === 'string' ? lastAsst.content : JSON.stringify(lastAsst.content);
  const result = await copyToClipboard(text);
  if (result.ok) console.log(`  ${green('✓')} Copied ${text.length} chars via ${cyan(result.via)}`);
  else console.log(`  ${yellow('!')} Copy failed: ${result.error || 'no clipboard available'}`);
}

async function handleSlashExport(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const target = rest[0] || path.join(ctx.cwd, `makestudio-session-${new Date().toISOString().slice(0, 19).replace(/[:.]/g, '-')}.md`);
  const absTarget = path.isAbsolute(target) ? target : path.join(ctx.cwd, target);
  const lines: string[] = [];
  lines.push(`# MakeStudio session`);
  lines.push(`Exported: ${new Date().toISOString()}`);
  lines.push(`Cwd: ${ctx.cwd}`);
  lines.push(`User: ${ctx.user?.email || '(not logged in)'}`);
  lines.push(`Model: ${ctx.providerInfo?.provider || '?'}/${ctx.providerInfo?.model || '?'}`);
  lines.push('');
  lines.push('---');
  for (const m of ctx.messages) {
    const body = typeof m.content === 'string' ? m.content : JSON.stringify(m.content, null, 2);
    lines.push('');
    lines.push(m.role === 'user' ? `## You` : `## Assistant`);
    lines.push('');
    lines.push(body);
  }
  try {
    fs.mkdirSync(path.dirname(absTarget), { recursive: true });
    fs.writeFileSync(absTarget, lines.join('\n'), 'utf8');
    console.log(`  ${green('✓')} Exported ${ctx.messages.length} message(s) → ${cyan(path.relative(ctx.cwd, absTarget))}`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Export failed: ${err.message}`);
  }
}

async function handleSlashRename(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const title = rest.join(' ').trim();
  if (!title) { console.log(`  ${dim('Usage: /rename <new title>')}`); return; }
  const { currentSessionFile, renameSession } = require('../sessions');
  const f = currentSessionFile(ctx);
  if (!f) { console.log(`  ${yellow('!')} No active session file.`); return; }
  const ok = renameSession(f, title);
  if (ok) console.log(`  ${green('✓')} Session renamed to ${cyan(title)}`);
  else console.log(`  ${yellow('!')} Rename failed.`);
}

async function handleSlashUndoFile(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const target = rest.join(' ').trim();
  if (!target) { console.log(`  ${yellow('!')} Usage: /undo-file <path>`); return; }
  const abs = path.isAbsolute(target) ? target : path.resolve(ctx.cwd, target);
  const { restoreFile } = require('../file-history');
  const r = restoreFile(ctx.cwd, abs);
  if (r.restored) {
    if (r.deleted) console.log(`  ${green('✓')} Deleted ${cyan(abs)} (rolled back creation). Snapshot ${dim(r.from)} consumed.`);
    else console.log(`  ${green('✓')} Restored ${cyan(abs)} from snapshot ${dim(r.from)}`);
  } else {
    console.log(`  ${yellow('!')} ${r.reason}`);
  }
}

async function handleSlashHistoryFile(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const target = rest.join(' ').trim();
  if (!target) { console.log(`  ${yellow('!')} Usage: /history-file <path>`); return; }
  const abs = path.isAbsolute(target) ? target : path.resolve(ctx.cwd, target);
  const { listFileHistory } = require('../file-history');
  const snaps = listFileHistory(ctx.cwd, abs);
  if (snaps.length === 0) { console.log(`  ${dim('(no snapshots for ' + abs + ')')}`); return; }
  console.log(`  ${bold('Snapshots for')} ${cyan(abs)}`);
  for (let i = 0; i < snaps.length; i++) {
    const s = snaps[snaps.length - 1 - i]; // newest first
    const age = Math.round((Date.now() - new Date(s.createdAt).getTime()) / 1000);
    const ageStr = age < 60 ? `${age}s` : age < 3600 ? `${Math.round(age/60)}m` : `${Math.round(age/3600)}h`;
    console.log(`  ${dim('['+i+']')} ${s.file.padEnd(40)} ${dim(ageStr + ' ago · ' + s.sizeBytes + 'B')}`);
  }
  console.log(`  ${dim('use: /undo-file ' + abs + '  (restores newest = [0])')}`);
}

async function handleSlashRecord(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const sub = rest[0];
  const { startRecording, stopRecording, recordingStatus } = require('../cassettes');
  if (!sub || sub === 'status') {
    const s = recordingStatus(ctx);
    if (!s.active) { console.log(`  ${dim('(not recording — /record start <name>)')}`); return; }
    console.log(`  ${green('●')} recording ${cyan(s.name)} · ${s.turns} turn(s) captured since ${dim(s.startedAt)}`);
    return;
  }
  if (sub === 'start') {
    const name = rest.slice(1).join(' ').trim() || `session-${Date.now()}`;
    try { startRecording(ctx, name); console.log(`  ${green('●')} recording started — ${cyan(name)}`); }
    catch (e: any) { console.log(`  ${yellow('!')} ${e.message}`); }
    return;
  }
  if (sub === 'stop') {
    try { const p = stopRecording(ctx); console.log(`  ${green('✓')} cassette saved: ${cyan(p)}`); }
    catch (e: any) { console.log(`  ${yellow('!')} ${e.message}`); }
    return;
  }
  console.log(`  ${yellow('!')} Usage: /record start [name] | /record stop | /record status`);
}

async function handleSlashReplay(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const name = rest.join(' ').trim();
  if (!name) { console.log(`  ${dim('Usage: /replay <name>')}`); return; }
  const { replayCassette } = require('../cassettes');
  try {
    const count = replayCassette(ctx, name);
    console.log(`  ${green('✓')} Replayed ${count} turn(s) from cassette ${cyan(name)}`);
    console.log(`  ${dim('(ctx.messages hydrated — continue the conversation or /clear to reset)')}`);
  } catch (e: any) { console.log(`  ${yellow('!')} ${e.message}`); }
}

async function handleSlashTrajectory(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const sub = (rest[0] || '').toLowerCase();
  const { listTrajectories, readTrajectory, exportTrajectoryBundle, getCurrentSessionId } = require('../trajectory');
  if (sub === 'list' || sub === 'ls' || !sub) {
    const all = listTrajectories();
    if (all.length === 0) {
      console.log(`  ${dim('(no trajectories — events accumulate as you chat)')}`);
      return;
    }
    console.log(`  ${bold('Trajectories')}`);
    for (const t of all) {
      const size = t.bytes > 1024 ? `${Math.round(t.bytes / 1024)}KB` : `${t.bytes}B`;
      const id = t.sessionId.slice(0, 12);
      console.log(`  ${dim('*')} ${cyan(id)} ${dim(t.lastEventAt?.slice(0, 19) || '')} · ${t.events} event(s) · ${size}`);
    }
    return;
  }
  if (sub === 'show') {
    const target = rest.slice(1).join(' ').trim() || getCurrentSessionId(ctx);
    if (!target) { console.log(`  ${yellow('!')} Usage: /trajectory show <session-id>`); return; }
    const events = readTrajectory(target);
    if (!events) { console.log(`  ${yellow('!')} No trajectory for ${target}`); return; }
    console.log(`  ${bold(`Trajectory ${target.slice(0, 12)}`)} ${dim(`(${events.length} events)`)}`);
    for (const e of events) {
      const ts = (e.ts || '').slice(11, 19);
      console.log(`  ${dim(`#${String(e.seq).padStart(3, '0')} ${ts}`)} ${cyan(e.source)}/${e.type}`);
      if (e.data) {
        const preview = JSON.stringify(e.data).slice(0, 140);
        console.log(`      ${dim(preview)}`);
      }
    }
    return;
  }
  if (sub === 'export') {
    const target = rest.slice(1).join(' ').trim() || getCurrentSessionId(ctx);
    if (!target) { console.log(`  ${yellow('!')} Usage: /trajectory export <session-id>`); return; }
    const out = exportTrajectoryBundle(target, ctx.cwd);
    if (out) console.log(`  ${green('✓')} Bundle written to ${cyan(out)}`);
    else console.log(`  ${yellow('!')} No trajectory for ${target}`);
    return;
  }
  console.log(`  ${dim('Usage:')} /trajectory ${cyan('list')} | ${cyan('show')} ${dim('[id]')} | ${cyan('export')} ${dim('[id]')}`);
}

async function handleSlashCassettes(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { listCassettes, deleteCassette } = require('../cassettes');
  if (rest[0] === 'rm' || rest[0] === 'remove') {
    const target = rest.slice(1).join(' ').trim();
    if (!target) { console.log(`  ${yellow('!')} Usage: /cassettes rm <name>`); return; }
    if (deleteCassette(target)) console.log(`  ${green('✓')} Removed ${target}`);
    else console.log(`  ${yellow('!')} No such cassette: ${target}`);
    return;
  }
  const all = listCassettes();
  if (all.length === 0) { console.log(`  ${dim('(no cassettes — /record start to create one)')}`); return; }
  console.log(`  ${bold('Cassettes')}`);
  for (const c of all) {
    const size = c.sizeBytes > 1024 ? `${Math.round(c.sizeBytes / 1024)}KB` : `${c.sizeBytes}B`;
    console.log(`  ${dim('*')} ${cyan(c.name.padEnd(30))} ${dim(c.recordedAt.slice(0, 19))} · ${c.turns} turn(s) · ${size}`);
  }
}

async function handleSlashExportSvg(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const out = rest.join(' ').trim();
  const target = out || path.join(ctx.cwd, `makestudio-export-${Date.now()}.svg`);
  const { ansiToSvg } = require('../ansi-to-svg');
  // Build a plain-text transcript of recent ctx.messages with light
  // ANSI coloring so the SVG reflects turn structure.
  const last = ctx.messages.slice(-30);
  const ansiLines: string[] = [];
  for (const m of last) {
    const role = m.role === 'user' ? '\x1b[36m> \x1b[0m' : m.role === 'assistant' ? '\x1b[37m' : '\x1b[90m';
    const content = typeof m.content === 'string' ? m.content : JSON.stringify(m.content);
    ansiLines.push(role + content + '\x1b[0m');
  }
  const svg = ansiToSvg(ansiLines.join('\n'));
  try {
    fs.writeFileSync(target, svg, 'utf8');
    const size = fs.statSync(target).size;
    console.log(`  ${green('✓')} SVG written to ${cyan(target)} ${dim('(' + size + 'B, ' + last.length + ' turn(s))')}`);
  } catch (e: any) {
    console.log(`  ${yellow('!')} Write failed: ${e.message}`);
  }
}

async function handleSlashSearch(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const q = rest.join(' ').trim();
  if (!q) { console.log(`  ${dim('Usage: /search <query>')}`); return; }
  console.log(`  ${dim('(searching sessions, might take a moment…)')}`);
  const { agenticSessionSearch } = require('../session-search');
  try {
    const hits = await agenticSessionSearch(q, ctx);
    if (hits.length === 0) {
      console.log(`  ${dim('(no relevant sessions found)')}`);
      return;
    }
    console.log(`  ${bold('Found ' + hits.length + ' relevant session(s) for')} ${cyan('"' + q + '"')}`);
    for (const h of hits.slice(0, 20)) {
      const id = h.summary.sessionId.slice(0, 8);
      const title = h.summary.title || h.summary.firstUserMessage?.slice(0, 60) || '(no title)';
      const tagPart = h.summary.tag ? (h.tagMatch ? yellow(' #' + h.summary.tag) : dim(' #' + h.summary.tag)) : '';
      console.log(`  ${cyan('[' + (h.rank + 1) + ']')} ${cyan(id)} ${title}${tagPart} ${dim(h.summary.startedAt.slice(0, 10))}`);
    }
    console.log(`  ${dim('resume: makestudio --resume <id>')}`);
  } catch (e: any) {
    console.log(`  ${yellow('!')} ${e.message}`);
  }
}

async function handleSlashTag(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const { currentSessionFile, getCurrentSessionTag, toggleSessionTag, getSessionTagsIndex } = require('../sessions');
  const file = currentSessionFile(ctx);
  const arg = rest.join(' ').trim();

  if (!arg) {
    const current = file ? getCurrentSessionTag(file) : null;
    const index = getSessionTagsIndex(ctx.cwd);
    console.log(`  ${bold('Current tag')}: ${current ? cyan('#' + current) : dim('(none)')}`);
    const tags = Object.keys(index);
    if (tags.length > 0) {
      console.log(`  ${bold('All tags in this cwd')}:`);
      for (const t of tags.sort()) console.log(`    ${cyan('#' + t)} ${dim('(' + index[t].length + ' session(s))')}`);
    }
    console.log(`  ${dim('Usage: /tag <name> — add/replace. Same name again removes (toggle).')}`);
    return;
  }
  if (!file) { console.log(`  ${yellow('!')} No active session file yet. Send a message first.`); return; }
  const result = toggleSessionTag(file, arg);
  const sanitized = arg.replace(/\s+/g, '-');
  if (result === 'added')    console.log(`  ${green('✓')} Tagged session with ${cyan('#' + sanitized)}`);
  else if (result === 'replaced') console.log(`  ${green('✓')} Replaced previous tag with ${cyan('#' + sanitized)}`);
  else if (result === 'removed')  console.log(`  ${green('✓')} Removed tag ${cyan('#' + sanitized)}`);
  else console.log(`  ${yellow('!')} Invalid tag name.`);
}

async function handleSlashFork(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // Port of Claude Code's /branch (conversation fork). We keep our
  // existing /branch as a git-branch helper to preserve muscle memory,
  // and use /fork for the conversation-copy behaviour — Claude Code
  // accepts both names as aliases anyway.
  const { forkSession } = require('../sessions');
  const title = rest.join(' ').trim() || undefined;
  const res = forkSession(ctx, title);
  if (!res) {
    console.log(`  ${yellow('!')} Nothing to fork — no session file yet. Send a message first.`);
    return;
  }
  console.log(`  ${green('✓')} Branched conversation (${res.messageCount} message(s) copied).`);
  console.log(`  ${dim('new session:')} ${cyan(res.newSessionId)}`);
  console.log(`  ${dim('resume original:')} ${cyan('makestudio --resume ' + res.oldSessionId)}`);
}

async function handleSlashSummary(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // `/summary write` → call the LLM to produce a PR-style summary
  // and persist it to the session header. `/summary` (no args) keeps
  // the existing stats listing — that's pure local and free.
  const sub = (rest[0] || '').toLowerCase();
  if (sub === 'write' || sub === 'gen' || sub === 'generate' || sub === 'pr') {
    const { generateSessionSummary } = require('../ai/summary-gen');
    console.log(`  ${dim('Generating PR-style summary…')}`);
    const summary = await generateSessionSummary(ctx);
    if (summary) {
      console.log();
      console.log(`  ${green('✓')} ${bold('Summary saved to session header')}`);
      console.log();
      for (const line of summary.split('\n')) console.log(`  ${line}`);
      console.log();
    } else {
      console.log(`  ${yellow('!')} Could not generate summary (no messages, no provider, or write failed).`);
    }
    return;
  }
  const userMsgs = ctx.messages.filter(m => m.role === 'user').length;
  const asstMsgs = ctx.messages.filter(m => m.role === 'assistant').length;
  console.log(`  ${bold('Session summary')}`);
  console.log(`  ${dim('cwd:')}      ${ctx.cwd}`);
  console.log(`  ${dim('user:')}     ${ctx.user?.email || '(anon)'}`);
  console.log(`  ${dim('model:')}    ${ctx.providerInfo?.provider || '?'}/${ctx.providerInfo?.model || '?'}`);
  console.log(`  ${dim('effort:')}   ${ctx.effort}`);
  console.log(`  ${dim('project:')}  ${ctx.activeProject?.name || '(none)'}`);
  console.log(`  ${dim('messages:')} ${ctx.messages.length} (${userMsgs} user · ${asstMsgs} assistant)`);
  console.log(`  ${dim('tokens:')}   ${ctx.usage.totalTokens.toLocaleString()}  (prompt ${ctx.usage.promptTokens.toLocaleString()} · completion ${ctx.usage.completionTokens.toLocaleString()})`);
  console.log(`  ${dim('cache:')}    reads ${ctx.usage.cacheReads.toLocaleString()} · writes ${ctx.usage.cacheWrites.toLocaleString()}`);
  console.log(`  ${dim('requests:')} ${ctx.usage.requestCount}`);
  if (ctx.messages.length > 0) {
    const firstUser = ctx.messages.find(m => m.role === 'user');
    if (firstUser) {
      const preview = (typeof firstUser.content === 'string' ? firstUser.content : '').slice(0, 100);
      console.log(`  ${dim('started:')}  "${preview}${preview.length >= 100 ? '…' : ''}"`);
    }
  }
}

async function handleSlashContinue(sc: SlashContext): Promise<void> {
  const { ctx, rest, cmd } = sc;
  const { listSessions, loadSessionMessages, bindSessionFile, currentSessionFile } = require('../sessions');
  const sub = (rest[0] || '').toLowerCase();

  // /continue — resume most recent if different from current; else just list
  if (cmd === '/continue' && !sub) {
    const list = listSessions(ctx.cwd, 1);
    const most = list[0];
    if (!most) {
      console.log(`  ${dim('Nenhuma sessao anterior neste diretorio.')}`);
      return;
    }
    if (currentSessionFile(ctx) === most.file) {
      console.log(`  ${dim('Ja estou na sessao mais recente deste diretorio.')}`);
      return;
    }
    try {
      const msgs = loadSessionMessages(most.file);
      ctx.clearConversation();
      ctx.messages.push(...msgs);
      bindSessionFile(ctx, most.file);
      console.log(`  ${green('✓')} Retomada: ${cyan(most.sessionId.slice(0, 8))} (${msgs.length} mensagens, iniciada ${most.startedAt})`);
    } catch (err: any) {
      console.log(`  ${yellow('!')} Falhou ao retomar: ${err.message}`);
    }
    return;
  }

  // /sessions — list and optionally resume by index/uuid
  const list = listSessions(ctx.cwd, 30);
  if (list.length === 0) {
    console.log(`  ${dim('Nenhuma sessao anterior neste diretorio.')}`);
    return;
  }

  if (sub) {
    // /sessions <id-or-prefix> OR /sessions <number>
    let target = list.find((s: any) => s.sessionId === sub || s.sessionId.startsWith(sub));
    if (!target) {
      const idx = parseInt(sub, 10);
      if (!isNaN(idx) && idx >= 1 && idx <= list.length) target = list[idx - 1];
    }
    if (!target) {
      console.log(`  ${yellow('!')} Sessao "${sub}" nao encontrada.`);
      return;
    }
    try {
      const msgs = loadSessionMessages(target.file);
      ctx.clearConversation();
      ctx.messages.push(...msgs);
      bindSessionFile(ctx, target.file);
      console.log(`  ${green('✓')} Retomada: ${cyan(target.sessionId.slice(0, 8))} (${msgs.length} mensagens)`);
    } catch (err: any) {
      console.log(`  ${yellow('!')} Falhou ao retomar: ${err.message}`);
    }
  } else {
    // List
    console.log(`  ${bold('Sessoes em')} ${cyan(ctx.cwd)}`);
    console.log('');
    const current = currentSessionFile(ctx);
    list.forEach((s: any, i: number) => {
      const mark = s.file === current ? green('●') : dim('○');
      const idStr = cyan(s.sessionId.slice(0, 8));
      const num = cyan(String(i + 1).padStart(2));
      const preview = (s.firstUserMessage || '').replace(/\n/g, ' ').slice(0, 60);
      console.log(`    ${mark} ${num}  ${idStr}  ${dim(s.lastUpdatedAt.slice(0, 19))}  ${dim(`${s.messageCount} msgs`)}  ${preview}`);
    });
    console.log('');
    console.log(`  ${dim('Use')} ${cyan('/sessions <numero-ou-id>')} ${dim('para retomar.')}`);
  }
}

async function handleSlashCompact(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  const { compactNow } = require('../ai/chat');
  try {
    const r = await compactNow(ctx);
    if (r.compacted) {
      console.log(`  ${green('*')} Historico resumido: ${r.before} → ${r.after} mensagens (ctx ~${r.pct.toFixed(1)}%)`);
    } else {
      console.log(`  ${dim(`Nada a compactar (${r.before} msgs, ctx ~${r.pct.toFixed(1)}%)`)}`);
    }
  } catch (err: any) {
    console.log(`  ${yellow('!')} compact falhou: ${err.message}`);
  }
}

async function handleSlashPaste(sc: SlashContext): Promise<void> {
  const { readClipboardImage } = require('../image-paste');
  const result = readClipboardImage();
  if (result.ok) {
    // Compact one-liner: marker + size. Path/mime/queue-count are
    // internal detail the user doesn't need every time they paste.
    console.log(`  ${cyan('[Image #' + result.attached.id + ']')} ${dim(`(${Math.round(result.attached.bytes / 1024)}KB)`)}`);
  } else {
    console.log(`  ${yellow('!')} ${result.reason}`);
  }
}

async function handleSlashUndoCompact(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  // Restore messages from the most recent pre-compact checkpoint.
  // Index argument (if any): 0 = newest, 1 = second-newest, etc.
  const { listCheckpoints, restoreCheckpoint } = require('../ai/compact-checkpoints');
  const idx = Math.max(0, parseInt(argsStr.trim(), 10) || 0);
  const before = ctx.messages.length;
  const list = listCheckpoints((ctx as any).sessionId);
  if (list.length === 0) {
    console.log(`  ${dim('No compact checkpoints for this session.')}`);
    return;
  }
  const r = restoreCheckpoint(ctx, idx, (ctx as any).sessionId);
  if (r.restored) {
    console.log(`  ${green('*')} Restaurado checkpoint (${r.from?.reason}, ${before} → ${ctx.messages.length} msgs).`);
    console.log(`  ${dim(`Tirado em ${r.from?.at}. ${list.length - 1} checkpoint(s) restantes.`)}`);
  } else {
    console.log(`  ${yellow('!')} undo-compact: ${r.reason}`);
  }
}

async function handleSlashSave(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const fs = require('fs');
  const path = require('path');
  const os = require('os');
  const { execSync } = require('child_process');
  const name = rest[0] || `snapshot-${Date.now()}`;
  const snapshotsDir = path.join(os.homedir(), '.makestudio', 'snapshots');
  fs.mkdirSync(snapshotsDir, { recursive: true });
  const file = path.join(snapshotsDir, `${name}.json`);

  // Capture git state if there's an active project
  let gitState: any = null;
  if (ctx.activeProject?.localPath) {
    try {
      const cwd = ctx.activeProject.localPath;
      gitState = {
        sha: execSync('git rev-parse HEAD', { cwd, timeout: 5_000 }).toString().trim(),
        branch: execSync('git rev-parse --abbrev-ref HEAD', { cwd, timeout: 5_000 }).toString().trim(),
        status: execSync('git status --short', { cwd, timeout: 5_000 }).toString(),
        remote: execSync('git config --get remote.origin.url', { cwd, timeout: 5_000 }).toString().trim(),
      };
    } catch (err) { swallow(err); }
  }

  // Capture MCP server list (names only — actual state rebuilt on load)
  let mcpState: any = null;
  try {
    const { listMcpServers } = require('../mcp');
    mcpState = listMcpServers();
  } catch (err) { swallow(err); }

  // Capture last tool call + session attachments
  let attachmentsState: any = null;
  try {
    const { listSessionAttachments } = require('../attachments');
    attachmentsState = listSessionAttachments();
  } catch (err) { swallow(err); }

  const snapshot = {
    version: 2,
    createdAt: new Date().toISOString(),
    machine: { hostname: os.hostname(), platform: process.platform, arch: process.arch },
    activeProject: ctx.activeProject,
    provider: ctx.provider,
    effort: ctx.effort,
    messages: ctx.messages,
    usage: ctx.usage,
    approvedTools: [...ctx.approvedTools],
    autoApprove: ctx.autoApprove,
    lastUserMessage: ctx.lastUserMessage,
    lastToolCall: ctx.lastToolCall,
    gitState,
    mcpState,
    attachmentsState,
  };
  fs.writeFileSync(file, JSON.stringify(snapshot, null, 2));
  console.log(`  ${green('✓')} Snapshot salvo: ${cyan(file)}`);
  console.log(`  ${dim('Incluido:')} ${ctx.messages.length} msgs, git ${gitState?.sha?.slice(0, 8) || 'none'}, ${mcpState?.length || 0} MCP servers, ${attachmentsState?.length || 0} anexos`);
  console.log(`  ${dim('Para restaurar em outra maquina:')} ${cyan('/load ' + name)}`);
}

async function handleSlashLoad(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const fs = require('fs');
  const path = require('path');
  const os = require('os');
  const name = rest[0];
  if (!name) {
    const snapshotsDir = path.join(os.homedir(), '.makestudio', 'snapshots');
    if (!fs.existsSync(snapshotsDir)) {
      console.log(`  ${dim('Nenhum snapshot salvo.')}`);
      return;
    }
    const files = fs.readdirSync(snapshotsDir).filter((f: string) => f.endsWith('.json'));
    console.log();
    console.log(`  ${chalk.white.bold('Snapshots disponiveis')}`);
    console.log();
    for (const f of files) {
      try {
        const s = JSON.parse(fs.readFileSync(path.join(snapshotsDir, f), 'utf8'));
        console.log(`  ${cyan(f.replace(/\.json$/, ''))} ${dim(`(${s.messages?.length || 0} msgs, ${new Date(s.createdAt).toLocaleString('pt-BR')})`)}`);
      } catch (err) { swallow(err); }
    }
    console.log();
    console.log(`  ${dim('Uso:')} ${cyan('/load <nome>')}`);
    return;
  }
  const file = path.join(os.homedir(), '.makestudio', 'snapshots', `${name}.json`);
  if (!fs.existsSync(file)) {
    console.log(`  ${yellow('!')} Snapshot ${name} nao encontrado.`);
    return;
  }
  try {
    const s = JSON.parse(fs.readFileSync(file, 'utf8'));
    ctx.activeProject = s.activeProject;
    ctx.provider = s.provider || 'claude';
    ctx.effort = s.effort || 'medium';
    ctx.messages = s.messages || [];
    ctx.usage = s.usage || ctx.usage;
    ctx.approvedTools = new Set(s.approvedTools || []);
    ctx.autoApprove = s.autoApprove || false;
    ctx.lastUserMessage = s.lastUserMessage || '';
    if (s.lastToolCall) ctx.lastToolCall = s.lastToolCall;

    console.log(`  ${green('✓')} Snapshot ${cyan(name)} restaurado. ${ctx.messages.length} msgs, effort=${ctx.effort}.`);

    // v2 snapshot: warn if git state differs
    if (s.gitState && ctx.activeProject?.localPath) {
      try {
        const { execSync } = require('child_process');
        const cwd = ctx.activeProject.localPath;
        const currentSha = execSync('git rev-parse HEAD', { cwd, timeout: 5_000 }).toString().trim();
        if (currentSha !== s.gitState.sha) {
          console.log(`  ${yellow('!')} Git divergiu: snapshot ${dim(s.gitState.sha.slice(0, 8))} vs atual ${dim(currentSha.slice(0, 8))}`);
          console.log(`  ${dim('   Para reproduzir exato:')} ${cyan(`git checkout ${s.gitState.sha.slice(0, 12)}`)}`);
        }
      } catch (err) { swallow(err); }
    }

    if (s.mcpState && s.mcpState.length > 0) {
      console.log(`  ${dim('MCP servers no snapshot:')} ${s.mcpState.map((m: any) => m.name).join(', ')}`);
      console.log(`  ${dim('(servers sao re-conectados no proximo chat)')}`);
    }

    if (s.machine && s.machine.hostname !== require('os').hostname()) {
      console.log(`  ${dim('Originalmente de')} ${s.machine.hostname} (${s.machine.platform})`);
    }
  } catch (err: any) {
    console.log(`  ${yellow('!')} Erro ao carregar: ${err.message}`);
  }
}

async function handleSlashResume(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withDetachedRepl(async () => {
    const { executeCommand } = require('../../commands/execute');
    const args = parseSlashArgs(argsStr);
    console.log(`  ${green('▶')} Retomando execucao (DUMs concluidos serao pulados automaticamente)`);
    await executeCommand({
      projectId: args.projectId || ctx.activeProject?.id,
      cli: args.cli || 'claude',
    });
  });
}

async function handleSlashRewind(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const target = rest[0];

  // Fase 2.4 — local file-snapshot rewind. Activated when rest[0] is
  // empty (list), a number (restore turn), or 'clear' (wipe checkpoints).
  // DarkFactory DUM rewind (below) is activated when rest[0] looks like
  // "DUM-NNN".
  const isDumRewind = typeof target === 'string' && /^DUM[-\s]*\d+$/i.test(target);
  if (!isDumRewind) {
    const { listCheckpoints, rewindToTurn, clearCheckpoints } = require('../rewind');
    const checkpoints = listCheckpoints(ctx);

    if (!target) {
      if (checkpoints.length === 0) {
        console.log(`  ${dim('Nenhum checkpoint nesta sessão ainda. Edite algo primeiro.')}`);
        console.log();
        console.log(`  ${dim('Uso:')}`);
        console.log(`    ${cyan('/rewind <N>')}      ${dim('restaura arquivos do turn N (e todos posteriores)')}`);
        console.log(`    ${cyan('/rewind clear')}    ${dim('apaga todos os checkpoints da sessão')}`);
        console.log(`    ${cyan('/rewind DUM-NNN')}  ${dim('(DarkFactory) reseta tasks de DUM em diante')}`);
        return;
      }
      console.log(`  ${bold('Checkpoints disponíveis')} ${dim('(oldest → newest)')}`);
      for (const cp of checkpoints) {
        const when = cp.startedAt.slice(11, 19);
        const preview = cp.userMessage.replace(/\s+/g, ' ').slice(0, 80);
        const changed = cp.files.length;
        console.log(`  ${cyan(String(cp.turn).padStart(3))}  ${dim(when)}  ${changed > 0 ? green(String(changed) + ' file(s)') : dim('no edits')}  ${dim('·')} ${preview}${preview.length >= 80 ? '…' : ''}`);
      }
      console.log();
      console.log(`  ${dim('Restaurar:')} ${cyan('/rewind <N>')}`);
      return;
    }

    if (target.toLowerCase() === 'clear') {
      const { askTuiOrReadline } = require('../tui/bridge');
      const ans = (await askTuiOrReadline(`Apagar ${checkpoints.length} checkpoint(s) da sessão? [S/n]`)).toLowerCase();
      if (ans && ans !== 's' && ans !== 'y' && ans !== '') { console.log(`  ${dim('Cancelado.')}`); return; }
      const { removed } = clearCheckpoints(ctx);
      console.log(`  ${green('✓')} ${removed} checkpoint(s) removido(s).`);
      return;
    }

    const n = parseInt(target, 10);
    if (!Number.isFinite(n) || n < 1) {
      console.log(`  ${yellow('!')} Argumento inválido. Use ${cyan('/rewind <N>')} (N = número do turn) ou ${cyan('/rewind clear')}.`);
      return;
    }
    const cp = checkpoints.find((c: any) => c.turn === n);
    if (!cp) {
      console.log(`  ${yellow('!')} Turn ${n} não encontrado. Execute ${cyan('/rewind')} sem args para listar.`);
      return;
    }

    const willAffect = checkpoints.filter((c: any) => c.turn >= n).reduce((sum: number, c: any) => sum + c.files.length, 0);
    const { askTuiOrReadline } = require('../tui/bridge');
    const ans = (await askTuiOrReadline(
      `Vai restaurar ${willAffect} file-edit(s) dos turns ${n}+ e descartar mensagens a partir do turn ${n}. Continuar? [S/n]`,
    )).toLowerCase();
    if (ans && ans !== 's' && ans !== 'y' && ans !== '') { console.log(`  ${dim('Cancelado.')}`); return; }

    const res = rewindToTurn(ctx, n);
    if (res.error) { console.log(`  ${yellow('!')} ${res.error}`); return; }
    console.log(`  ${green('✓')} Rewind para turn ${n}.`);
    console.log(`    ${dim('files restored:')} ${green(String(res.filesRestored))}`);
    if (res.filesDeleted > 0) console.log(`    ${dim('files deleted:')}  ${red(String(res.filesDeleted))}`);
    console.log(`    ${dim('msgs dropped:')}   ${String(res.messagesDropped)}`);
    return;
  }

  // Legacy DarkFactory /rewind DUM-NNN path unchanged below.
  if (!ctx.activeProject) {
    console.log(`  ${yellow('!')} Nenhum projeto ativo. Use ${cyan('/project <id>')} primeiro.`);
    return;
  }
  const { getApiClient } = require('../../network/api-client');
  const api = getApiClient();
  try {
    const dumsRes = await api.get(`/dark-factory/dums/project/${ctx.activeProject.id}`, {
      headers: { 'x-tenant-id': ctx.user?.tenantId || 'staff' },
      timeout: 10_000,
    });
    const dums = dumsRes.data?.data || dumsRes.data || [];
    const sorted = [...dums].sort((a: any, b: any) => {
      const na = parseInt((a.dumNumber || '').match(/\d+/)?.[0] || '9999', 10);
      const nb = parseInt((b.dumNumber || '').match(/\d+/)?.[0] || '9999', 10);
      return na - nb;
    });
    const targetNum = parseInt(target.match(/\d+/)?.[0] || '0', 10);
    const toReset = sorted.filter((d: any) => {
      const n = parseInt((d.dumNumber || '').match(/\d+/)?.[0] || '9999', 10);
      return n >= targetNum;
    });
    if (toReset.length === 0) {
      console.log(`  ${yellow('!')} DUM ${target} nao encontrado.`);
      return;
    }
    const { askTuiOrReadline } = require('../tui/bridge');
    const ans = (await askTuiOrReadline(`Vai resetar ${toReset.length} DUM(s) (${toReset[0].dumNumber} em diante) para pending. Continuar? [S/n]`)).toLowerCase();
    if (ans && ans !== 's' && ans !== 'y' && ans !== '') {
      console.log(`  ${dim('Cancelado.')}`);
      return;
    }
    let resetCount = 0;
    for (const d of toReset) {
      for (const task of (d.tasks || [])) {
        try {
          await api.put(`/dark-factory/tasks/${task.id}`, { status: 'pending' }, { timeout: 5_000 });
          resetCount++;
        } catch (err) { swallow(err); }
      }
    }
    console.log(`  ${green('✓')} ${resetCount} tasks resetadas para pending. Use ${cyan('/resume')} para re-executar.`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Erro: ${err.message}`);
  }
}

async function handleSlashRetry(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Find last user message and re-run it
  const lastUser = [...ctx.messages].reverse().find(m => m.role === 'user');
  if (!lastUser) {
    console.log(`  ${yellow('!')} Sem mensagem anterior para regenerar.`);
    return;
  }
  // Remove last assistant message(s) after the last user message
  const lastUserIdx = ctx.messages.lastIndexOf(lastUser);
  ctx.messages = ctx.messages.slice(0, lastUserIdx);
  const { handleAIChat } = require('../ai/chat');
  await handleAIChat(typeof lastUser.content === 'string' ? lastUser.content : ctx.lastUserMessage, ctx);
}

async function handleSlashEdit(sc: SlashContext): Promise<void> {
  const { ctx, trimmed } = sc;
  // /edit <new text> — replace last user message and retry
  const newText = trimmed.replace(/^\/edit\s*/, '').trim();
  if (!newText) {
    console.log(`  ${dim('Uso:')} ${cyan('/edit <novo texto>')}`);
    return;
  }
  const lastUser = [...ctx.messages].reverse().find(m => m.role === 'user');
  if (!lastUser) {
    console.log(`  ${yellow('!')} Sem mensagem anterior para editar.`);
    return;
  }
  const lastUserIdx = ctx.messages.lastIndexOf(lastUser);
  ctx.messages = ctx.messages.slice(0, lastUserIdx);
  const { handleAIChat } = require('../ai/chat');
  await handleAIChat(newText, ctx);
}

async function handleSlashUndo(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Remove last exchange (last user msg + subsequent assistant msgs)
  let removed = 0;
  while (ctx.messages.length > 0) {
    const last = ctx.messages.pop();
    removed++;
    if (last?.role === 'user') return;
  }
  console.log(`  ${green('✓')} Removidas ${removed} mensagem(ns). Ultima interacao desfeita.`);
}

async function handleSlashHistory(sc: SlashContext): Promise<void> {
  const { argsStr } = sc;
  await withExitGuard(async () => {
    const { historyCommand } = require('../../commands/history');
    const args = parseSlashArgs(argsStr);
    await historyCommand({ limit: args.limit || '50', projectId: args.projectId });
  });
}


export const SESSION_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/clear'], handler: handleSlashClear },
  { names: ['/copy'], handler: handleSlashCopy },
  { names: ['/export'], handler: handleSlashExport },
  { names: ['/rename'], handler: handleSlashRename },
  { names: ['/undo-file'], handler: handleSlashUndoFile },
  { names: ['/history-file'], handler: handleSlashHistoryFile },
  { names: ['/record'], handler: handleSlashRecord },
  { names: ['/replay'], handler: handleSlashReplay },
  { names: ['/trajectory'], handler: handleSlashTrajectory },
  { names: ['/cassettes'], handler: handleSlashCassettes },
  { names: ['/export-svg'], handler: handleSlashExportSvg },
  { names: ['/search'], handler: handleSlashSearch },
  { names: ['/tag'], handler: handleSlashTag },
  { names: ['/fork'], handler: handleSlashFork },
  { names: ['/summary'], handler: handleSlashSummary },
  { names: ['/continue', '/sessions'], handler: handleSlashContinue },
  { names: ['/compact', '/summarize'], handler: handleSlashCompact },
  { names: ['/paste', '/paste-image'], handler: handleSlashPaste },
  { names: ['/undo-compact', '/uncompact'], handler: handleSlashUndoCompact },
  { names: ['/save'], handler: handleSlashSave },
  { names: ['/load'], handler: handleSlashLoad },
  { names: ['/resume'], handler: handleSlashResume },
  { names: ['/rewind'], handler: handleSlashRewind },
  { names: ['/retry', '/regenerate'], handler: handleSlashRetry },
  { names: ['/edit'], handler: handleSlashEdit },
  { names: ['/undo'], handler: handleSlashUndo },
  { names: ['/history'], handler: handleSlashHistory },
];
