/**
 * Slash command handlers — system topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `SYSTEM_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashHelp(sc: SlashContext): Promise<void> {
  printHelp();
}

async function handleSlashQuit(sc: SlashContext): Promise<void> {
  const { rl } = sc;
  rl.close();
}

async function handleSlashLogout(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  await withExitGuard(async () => {
    const { logoutCommand } = require('../../commands/logout');
    await logoutCommand();
    ctx.token = null;
    ctx.user = null;
  });
}

async function handleSlashExecute(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withDetachedRepl(async () => {
    const { executeCommand } = require('../../commands/execute');
    const args = parseSlashArgs(argsStr);
    await executeCommand({
      projectId: args.projectId || ctx.activeProject?.id,
      cli: args.cli || 'claude',
      skipCheckpoint: args.skipCheckpoint === 'true',
      onlyDum: args.onlyDum,
      dryRun: args.dryRun === 'true',
    });
  });
}

async function handleSlashRefine(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withDetachedRepl(async () => {
    const { refineCommand } = require('../../commands/refine');
    const args = parseSlashArgs(argsStr);
    await refineCommand({
      projectId: args.projectId || ctx.activeProject?.id,
      cli: args.cli,
      noDecompose: args.noDecompose === 'true',
      requirementsOnly: args.requirementsOnly === 'true',
      repo: args.repo,
    });
  });
}

async function handleSlashDoctor(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withDetachedRepl(async () => {
    const { doctorCommand } = require('../../commands/doctor');
    const args = parseSlashArgs(argsStr);
    await doctorCommand({
      projectId: args.projectId || ctx.activeProject?.id,
      cli: args.cli || 'claude',
      deep: args.deep === 'true',
      skipFix: args.skipFix === 'true',
      maxPasses: parseInt(args.maxPasses || '3', 10),
      repo: args.repo,
    });
  });
}

async function handleSlashBootstrap(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // Scaffold the project's `.makestudio/` directory. Idempotent —
  // existing files are left alone, only missing pieces fill in.
  const { bootstrapProject } = require('../project-bootstrap');
  const root = ctx.activeProject?.localPath || ctx.cwd;
  const r = bootstrapProject(root);
  console.log();
  if (r.created.length > 0) {
    console.log(`  ${green('✓')} Scaffolded ${cyan(r.rootDir)}`);
    for (const p of r.created) console.log(`    ${dim('+')} ${p}`);
  } else {
    console.log(`  ${dim('Already scaffolded — nothing to create.')}`);
  }
  if (r.skipped.length > 0) {
    console.log(`  ${dim(`Kept ${r.skipped.length} existing file(s).`)}`);
  }
  console.log();
  console.log(`  ${dim('See')} ${cyan('.makestudio/README.md')} ${dim('for what each subfolder is for.')}`);
  console.log();
}

async function handleSlashProjects(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  await handleProjectsList(ctx);
}

async function handleSlashProject(sc: SlashContext): Promise<void> {
  const { ctx, trimmed } = sc;
  await handleProjectSelect(trimmed, ctx);
}

async function handleSlashStatus(sc: SlashContext): Promise<void> {
  await withExitGuard(async () => {
    const { statusCommand } = require('../../commands/status');
    await statusCommand();
  });
}

async function handleSlashTasks(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withExitGuard(async () => {
    const { tasksCommand } = require('../../commands/tasks');
    const args = parseSlashArgs(argsStr);
    await tasksCommand({
      projectId: args.projectId || ctx.activeProject?.id,
      status: args.status,
    });
  });
}

async function handleSlashAnalyze(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await withExitGuard(async () => {
    const { analyzeCommand } = require('../../commands/analyze');
    const args = parseSlashArgs(argsStr);
    await analyzeCommand({
      path: args.path,
      deep: args.deep === 'true',
      audit: args.audit === 'true',
      cli: args.cli || 'claude',
      projectId: args.projectId || ctx.activeProject?.id,
    });
  });
}

async function handleSlashCommitPushPr(sc: SlashContext): Promise<void> {
  const { ctx, argsStr } = sc;
  await handleCommitPushPr(ctx, argsStr);
}

async function handleSlashPlugin(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const sub = rest[0]?.toLowerCase();
  await withExitGuard(async () => {
    if (!sub || sub === 'list') {
      const { pluginListCommand } = require('../../commands/plugin');
      await pluginListCommand();
    } else if (sub === 'install' && rest[1]) {
      const { pluginInstallCommand } = require('../../commands/plugin');
      await pluginInstallCommand(rest[1]);
    } else if (sub === 'remove' && rest[1]) {
      const { pluginRemoveCommand } = require('../../commands/plugin');
      await pluginRemoveCommand(rest[1]);
    } else if (sub === 'enable' && rest[1]) {
      const { pluginEnableCommand } = require('../../commands/plugin');
      await pluginEnableCommand(rest[1]);
    } else if (sub === 'disable' && rest[1]) {
      const { pluginDisableCommand } = require('../../commands/plugin');
      await pluginDisableCommand(rest[1]);
    } else {
      console.log(`  ${dim('Uso:')} ${cyan('/plugin')} ${dim('[list|install|remove|enable|disable] [nome]')}`);
    }
  });
}

async function handleSlashHealth(sc: SlashContext): Promise<void> {
  await withExitGuard(async () => {
    const { healthCommand } = require('../../commands/health');
    await healthCommand({});
  });
}

async function handleSlashBoilerplate(sc: SlashContext): Promise<void> {
  const { argsStr } = sc;
  await withExitGuard(async () => {
    const { boilerplateCommand } = require('../../commands/boilerplate');
    const args = parseSlashArgs(argsStr);
    await boilerplateCommand({ list: true, ...args });
  });
}

async function handleSlashKanban(sc: SlashContext): Promise<void> {
  const { argsStr } = sc;
  await withDetachedRepl(async () => {
    const { pluginRegistry } = require('../../core/plugin-registry');
    const cmds = pluginRegistry.getCommands();
    const kanban = cmds.find((c: any) => c.name === 'kanban');
    if (kanban) {
      await kanban.handler(parseSlashArgs(argsStr));
    } else {
      console.log(`  ${yellow('!')} Plugin kanban nao instalado.`);
    }
  });
}


async function handleSlashMemstat(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const dbg = require('../debug-log');
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { tuiLog } = require('../tui/bridge');
  const snap = dbg.captureMemSnapshot({ ctx, trigger: 'manual' });
  const fmtMB = (b: number) => `${(b / 1024 / 1024).toFixed(1)}MB`;
  const lines: string[] = [];
  lines.push(bold('Process memory:'));
  lines.push(`  rss=${fmtMB(snap.rss)}  heapUsed=${fmtMB(snap.heapUsed)}  heapTotal=${fmtMB(snap.heapTotal)}  external=${fmtMB(snap.external)}  arrayBuffers=${fmtMB(snap.arrayBuffers)}`);
  lines.push(bold('Chat history:'));
  lines.push(`  ctx.messages: ${snap.ctxMessagesCount ?? '?'} entries (${fmtMB(snap.ctxMessagesBytes ?? 0)})`);
  lines.push(bold('TUI state:'));
  lines.push(`  tui.messages: ${snap.tuiMessagesCount ?? '?'} entries (${fmtMB(snap.tuiMessagesBytes ?? 0)})`);
  lines.push(`  pastedTexts: ${snap.pastedTextsCount ?? 0} entries (${fmtMB(snap.pastedTextsBytes ?? 0)})`);
  lines.push(bold('Listeners (subscribe-without-unsubscribe leak suspects):'));
  lines.push(`  messageHooks=${snap.messageHooks ?? 0}  pickerListeners=${snap.pickerListeners ?? 0}  toastListeners=${snap.toastListeners ?? 0}`);
  lines.push(`  permListeners=${snap.permListeners ?? 0}  usageListeners=${snap.usageListeners ?? 0}  transientSubs=${snap.transientSubs ?? 0}`);
  lines.push(`  stdin.data=${snap.stdinListeners ?? 0}  stdout.drain=${snap.stdoutListeners ?? 0}`);
  lines.push(bold('Caches:'));
  lines.push(`  ctx.readCache=${snap.readCacheCount ?? 0}  readPaths=${snap.readPathsCount ?? 0}`);
  lines.push(`  lsp: diagFiles=${snap.lspDiagnosticFiles ?? 0}  diagEntries=${snap.lspDiagnosticEntries ?? 0}`);
  lines.push(`  subagentPool=${snap.subagentPoolSize ?? 0}  coordinatorWorkers=${snap.coordinatorWorkers ?? 0}`);
  const args = sc.input.trim().split(/\s+/).slice(1);
  if (args.includes('--heap')) {
    const out = dbg.dbgHeapSnapshot('manual');
    if (out) lines.push(green(`  heap snapshot → ${out}`));
    else lines.push(red('  heap snapshot failed (debug log disabled? — run with --debug)'));
  } else {
    lines.push(dim('  hint: `/memstat --heap` writes a heapsnapshot file for Chrome DevTools'));
  }
  tuiLog(lines.join('\n'), 'info');
}

export const SYSTEM_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/help', '/h'], handler: handleSlashHelp },
  { names: ['/quit', '/exit', '/q'], handler: handleSlashQuit },
  { names: ['/logout'], handler: handleSlashLogout },
  { names: ['/execute'], handler: handleSlashExecute },
  { names: ['/refine'], handler: handleSlashRefine },
  { names: ['/doctor'], handler: handleSlashDoctor },
  { names: ['/bootstrap'], handler: handleSlashBootstrap },
  { names: ['/projects'], handler: handleSlashProjects },
  { names: ['/project'], handler: handleSlashProject },
  { names: ['/status'], handler: handleSlashStatus },
  { names: ['/tasks'], handler: handleSlashTasks },
  { names: ['/analyze'], handler: handleSlashAnalyze },
  { names: ['/commit-push-pr', '/cpp'], handler: handleSlashCommitPushPr },
  { names: ['/plugin', '/plugins'], handler: handleSlashPlugin },
  { names: ['/health'], handler: handleSlashHealth },
  { names: ['/boilerplate', '/bp'], handler: handleSlashBoilerplate },
  { names: ['/kanban'], handler: handleSlashKanban },
  { names: ['/memstat'], handler: handleSlashMemstat },
];
