import { swallow } from '../../utils/log';
/**
 * Slash command handlers — ui topic.
 *
 * One handler per command. Registered into the slash-registry via
 * `UI_SLASH_COMMANDS` (collected by slash-handlers/index.ts).
 *
 * Generated by extraction; matches the original case bodies from
 * router.ts:routeInput verbatim apart from `break;` → `return;`.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { handleAIChat } from '../ai/chat';
import { printHelp, parseSlashArgs, handleProjectSelect, handleProjectsList, handleProviderSwitch, handleCostCommand, handleCtxCommand, handleModelCommand } from '../commands';
import { loadAllSkills } from '../skills';
import { loadSchedules, addSchedule, removeSchedule, toggleSchedule, computeNextRun } from '../schedule';
import { handleDiff, handleBranch, handleCommit, handleCommitPushPr } from '../git-commands';
import { executeCoordinatorTool } from '../ai/coordinator-tools';
import {
  dim, yellow, green, cyan, red, bold,
  ghPreflight, ghErrorHint,
  withDetachedRepl, withExitGuard,
} from '../slash-utils';
import type { SlashCommand, SlashContext } from '../slash-registry';



async function handleSlashReloadPlugins(sc: SlashContext): Promise<void> {
  try {
    const { pluginRegistry } = require('../../core/plugin-registry');
    const { loadAllPlugins } = require('../../core/plugin-manager');
    const before = pluginRegistry.count();
    pluginRegistry.clear();
    await loadAllPlugins();
    const after = pluginRegistry.count();
    console.log(`  ${green('✓')} Reloaded plugins: ${before} → ${after}`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Plugin reload failed: ${err.message}`);
  }
}

async function handleSlashAddDir(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  // Ported from Claude Code's /add-dir. Two modes:
  //   /add-dir <path>          — session-only (ctx.additionalDirs)
  //   /add-dir <path> --save   — also persist to settings.workingDirs
  //   /add-dir remove <path>   — drop from both session + settings
  //   /add-dir                 — list current dirs (session + persisted)
  const sub = rest[0];
  const { loadSettings, saveSettings } = require('../settings');

  if (!sub) {
    const persisted = loadSettings().workingDirs || [];
    const sessionOnly = ctx.additionalDirs.filter((d: string) => !persisted.includes(d));
    console.log(`  ${bold('Working dirs')}`);
    console.log(`  ${dim('*')} ${ctx.cwd} ${dim('(primary · cwd)')}`);
    for (const d of persisted) console.log(`  ${dim('*')} ${d} ${dim('(saved)')}`);
    for (const d of sessionOnly) console.log(`  ${dim('*')} ${d} ${dim('(session)')}`);
    if (persisted.length + sessionOnly.length === 0) {
      console.log(`  ${dim('(no extra working dirs — use /add-dir <path>)')}`);
    }
    return;
  }

  if (sub === 'remove' || sub === 'rm') {
    const target = rest[1];
    if (!target) { console.log(`  ${yellow('!')} Usage: /add-dir remove <path>`); return; }
    const abs = path.resolve(target);
    ctx.additionalDirs = ctx.additionalDirs.filter((d: string) => d !== abs);
    const s = loadSettings();
    if (s.workingDirs.includes(abs)) {
      saveSettings({ workingDirs: s.workingDirs.filter((d: string) => d !== abs) });
    }
    console.log(`  ${green('✓')} Removed ${cyan(abs)}`);
    return;
  }

  const dirArg = sub;
  const save = rest.includes('--save');
  const abs = path.resolve(dirArg);
  if (!fs.existsSync(abs)) { console.log(`  ${yellow('!')} Does not exist: ${abs}`); return; }
  if (!fs.statSync(abs).isDirectory()) { console.log(`  ${yellow('!')} Not a directory: ${abs}`); return; }
  if (path.resolve(abs) === path.resolve(ctx.cwd)) { console.log(`  ${dim('Already the primary cwd.')}`); return; }

  if (!ctx.additionalDirs.includes(abs)) ctx.additionalDirs.push(abs);
  if (save) {
    const s = loadSettings();
    if (!s.workingDirs.includes(abs)) saveSettings({ workingDirs: [...s.workingDirs, abs] });
  }
  console.log(`  ${green('✓')} Added ${cyan(abs)} ${dim(save ? '(persisted)' : '(session-only — add --save to persist)')}`);
}

async function handleSlashVim(sc: SlashContext): Promise<void> {
  const { loadSettings, saveSettings } = require('../settings');
  const s = loadSettings();
  const next = !s.vimMode;
  saveSettings({ vimMode: next });
  if (next) {
    console.log(`  ${green('✓')} Vim mode: ${cyan('ON')}  ${dim('(run /restart to apply)')}`);
    console.log(`  ${dim('Supported: modes INSERT/NORMAL, motions hlweb0$^ , commands xXpPurDCY, operators d/c/y + motion, dd/cc/yy, i/I/a/A/o/O')}`);
    console.log(`  ${dim('Not supported: counts (3w), j/k (single-line), f/F/t/T, text objects, gg/G, indent ><, dot-repeat')}`);
  } else {
    console.log(`  ${green('✓')} Vim mode: ${dim('off')}  ${dim('(run /restart to apply)')}`);
  }
}

async function handleSlashTheme(sc: SlashContext): Promise<void> {
  const { rest, command } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  // Derive the valid list from the actual palette registry so the
  // command never drifts from theme.ts. Hard-coding here was the
  // reason `code` (and earlier `classic`) errored as "invalid".
  const valid: string[] = (() => {
    try { return require('../theme').themeNames(); } catch (err) { swallow(err); }
    return ['default', 'classic', 'dark', 'light', 'monokai', 'dracula', 'solarized', 'fedora', 'ubuntu', 'arch', 'gruvbox', 'nord', 'code'];
  })();
  const arg = (rest[0] || '').toLowerCase();
  if (!arg) {
    const s = loadSettings();
    console.log(`  ${dim('Current:')} ${cyan(s.theme)}`);
    console.log(`  ${dim('Options:')} ${valid.join(', ')}`);
    return;
  }
  if (!valid.includes(arg)) { console.log(`  ${yellow('!')} Invalid theme. Options: ${valid.join(', ')}`); return; }
  saveSettings({ theme: arg as any });
  console.log(`  ${green('✓')} Theme: ${cyan(arg)}  ${dim('run /restart to apply')}`);
}

async function handleSlashColor(sc: SlashContext): Promise<void> {
  const { rest, input } = sc;
  // Mirrors Claude Code's `/color`. Output strings are kept verbatim
  // for parity ("Please provide a color." / "Session color set to:").
  // Tighter than `/theme` — swaps only the input border + bar accent.
  const { saveSettings } = require('../settings');
  const PUBLIC_COLORS = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'cyan', 'default'];
  const arg = (rest[0] || '').toLowerCase();
  if (!arg) {
    console.log(`  Please provide a color. Available colors: ${PUBLIC_COLORS.join(', ')}`);
    return;
  }
  if (!PUBLIC_COLORS.includes(arg)) {
    console.log(`  ${yellow('!')} Invalid color. Available colors: ${PUBLIC_COLORS.join(', ')}`);
    return;
  }
  saveSettings({ chatColor: arg as any });
  console.log(`  Session color set to: ${arg}`);
}

async function handleSlashKeybindings(sc: SlashContext): Promise<void> {
  const { rest } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const s = loadSettings();
  if (rest.length === 0) {
    console.log(`  ${bold('Current keybindings')}`);
    for (const [action, key] of Object.entries(s.keybindings)) {
      console.log(`  ${cyan(action.padEnd(18))} ${key}`);
    }
    console.log(`  ${dim('Set:')} /keybindings <action> <key>`);
    return;
  }
  if (rest.length < 2) { console.log(`  ${dim('Usage: /keybindings <action> <key>')}`); return; }
  const [action, ...keyParts] = rest;
  const key = keyParts.join(' ');
  if (!(action in s.keybindings)) {
    console.log(`  ${yellow('!')} Unknown action "${action}". Valid: ${Object.keys(s.keybindings).join(', ')}`);
    return;
  }
  saveSettings({ keybindings: { [action]: key } });
  console.log(`  ${green('✓')} ${action} → ${cyan(key)}  ${dim('run /restart to apply')}`);
}

async function handleSlashStatusline(sc: SlashContext): Promise<void> {
  const { ctx, rest } = sc;
  const { loadSettings, saveSettings } = require('../settings');
  const validFields: string[] = ['status', 'msgs', 'ctx', 'tokens', 'cache', 'todos', 'model', 'cwd', 'mode', 'style', 'rules', 'perms'];
  const s = loadSettings();
  if (rest.length === 0) {
    console.log(`  ${bold('Current status line fields')}`);
    console.log(`  ${cyan(s.statusline.fields.join(' · '))}`);
    console.log(`  ${dim('Valid:')} ${validFields.join(', ')}`);
    console.log(`  ${dim('Set:')} /statusline <field> <field> …`);
    return;
  }
  const fields = rest.filter(f => validFields.includes(f));
  if (fields.length === 0) { console.log(`  ${yellow('!')} No valid fields in: ${rest.join(' ')}`); return; }
  saveSettings({ statusline: { fields } });
  console.log(`  ${green('✓')} Status line: ${cyan(fields.join(' · '))}  ${dim('run /restart to apply')}`);
}

async function handleSlashEnv(sc: SlashContext): Promise<void> {
  const { ctx } = sc;
  const keys = [
    'HOME', 'USER', 'SHELL', 'NODE_ENV', 'EDITOR',
    'MAKESTUDIO_REPL', 'MAKESTUDIO_PLAIN',
    'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GROQ_API_KEY',
  ];
  console.log(`  ${bold('Environment')}`);
  for (const k of keys) {
    const v = process.env[k];
    if (!v) continue;
    const display = k.endsWith('_API_KEY') ? `${v.slice(0, 8)}…${v.slice(-4)}` : v;
    console.log(`  ${cyan(k.padEnd(22))} ${display}`);
  }
  console.log(`  ${dim('cwd:')}                   ${ctx.cwd}`);
  console.log(`  ${dim('platform:')}              ${process.platform}-${process.arch}`);
  console.log(`  ${dim('node:')}                  ${process.version}`);
}

async function handleSlashUpgrade(sc: SlashContext): Promise<void> {
  console.log(`  ${dim('Running: npm i -g @makestudio/agent@latest')}`);
  try {
    const { spawn } = require('child_process');
    const proc = spawn('npm', ['i', '-g', '@makestudio/agent@latest'], { stdio: 'inherit' });
    await new Promise<void>(resolve => proc.on('exit', () => resolve()));
    console.log(`  ${green('✓')} Done. Restart the REPL to use the new version.`);
  } catch (err: any) {
    console.log(`  ${yellow('!')} Upgrade failed: ${err.message}`);
  }
}

async function handleSlashRestart(sc: SlashContext): Promise<void> {
  const { input } = sc;
  // Re-exec the current process. Uses --continue so session state is
  // restored so user doesn't lose the conversation.
  //
  // TTY handling — learned the hard way:
  //  - tui-router already called destroyRepl() before routing here, so
  //    we DON'T double-destroy. A second Ink unmount leaves the TTY
  //    in a half-raw state → `setRawMode EIO` in the child.
  //  - Before spawn, explicitly cook the TTY (disable raw mode +
  //    pause stdin) so the child starts from a clean slate.
  //  - detached:false + parent stays alive (awaiting child.exit). The
  //    child inherits stdio and takes over the TTY; parent exits with
  //    the child's exit code. Detaching while sharing stdio caused the
  //    shell to fight the child for input.
  const { spawn } = require('child_process');
  console.log(`  ${dim('Restarting REPL…')}`);
  try {
    if (process.stdin.isTTY && (process.stdin as any).isRaw) {
      (process.stdin as any).setRawMode(false);
    }
  } catch (err) { swallow(err); }

  const argv = process.argv.slice(1);
  if (!argv.includes('-c') && !argv.includes('--continue') && !argv.some(a => a === '--resume')) {
    argv.push('--continue');
  }
  const child = spawn(process.execPath, argv, {
    stdio: 'inherit',
    detached: false,
    env: { ...process.env },
  });
  child.on('exit', (code: number | null) => process.exit(code ?? 0));
  await new Promise<void>(() => { /* parent waits for child */ });
  return;
}

async function handleSlashKeys(sc: SlashContext): Promise<void> {
  const { command, cmd, input } = sc;
  // Quick cheat-sheet for REPL keybindings. Pulls live values from
  // settings.keybindings so remapped keys show up correctly.
  const { loadSettings } = require('../settings');
  const kb = loadSettings().keybindings || {};
  console.log(`  ${bold('REPL keybindings')}`);
  console.log(`    ${cyan((kb.historyPrev || 'up').padEnd(16))} ${dim('history back (last command)')}`);
  console.log(`    ${cyan((kb.historyNext || 'down').padEnd(16))} ${dim('history forward')}`);
  console.log(`    ${cyan((kb.reverseSearch || 'ctrl+r').padEnd(16))} ${dim('reverse-search history (fuzzy)')}`);
  console.log(`    ${cyan((kb.tabComplete || 'tab').padEnd(16))} ${dim('autocomplete slash commands + @file')}`);
  console.log(`    ${cyan((kb.clearScreen || 'ctrl+l').padEnd(16))} ${dim('clear context + terminal scrollback')}`);
  console.log(`    ${cyan((kb.cancel || 'escape+escape').padEnd(16))} ${dim('cancel in-flight turn (double Esc)')}`);
  console.log(`    ${cyan((kb.exit || 'ctrl+c').padEnd(16))} ${dim('exit REPL')}`);
  console.log();
  console.log(`  ${bold('Input modes')}`);
  console.log(`    ${cyan('!cmd'.padEnd(16))} ${dim('run shell cmd directly, skip LLM')}`);
  console.log(`    ${cyan('@path'.padEnd(16))} ${dim('reference a file path — resolved before sending')}`);
  console.log(`    ${cyan('/x <arg>'.padEnd(16))} ${dim('slash command (Tab lists)')}`);
  console.log();
  console.log(`  ${bold('Mode switches')}`);
  console.log(`    ${cyan('/permission-mode')} ${dim('plan | acceptEdits | bypassPermissions | dontAsk | default')}`);
  console.log(`    ${cyan('/output-style')}    ${dim('terse | verbose | explain | code-only | default')}`);
  console.log(`    ${cyan('/effort')}          ${dim('low | medium | high | max')}`);
  console.log(`    ${cyan('/vim')}             ${dim('toggle vim-mode input')}`);
  console.log();
  console.log(`  ${bold('Scroll / TUI')}`);
  console.log(`    ${cyan('Shift+↑/↓'.padEnd(16))} ${dim('scroll history (older messages)')}`);
  console.log(`    ${cyan('Shift+PgUp/PgDn').padEnd(16)} ${dim('(if supported by your terminal)')}`);
}


export const UI_SLASH_COMMANDS: SlashCommand[] = [
  { names: ['/reload-plugins'], handler: handleSlashReloadPlugins },
  { names: ['/add-dir'], handler: handleSlashAddDir },
  { names: ['/vim'], handler: handleSlashVim },
  { names: ['/theme'], handler: handleSlashTheme },
  { names: ['/color'], handler: handleSlashColor },
  { names: ['/keybindings'], handler: handleSlashKeybindings },
  { names: ['/statusline'], handler: handleSlashStatusline },
  { names: ['/env'], handler: handleSlashEnv },
  { names: ['/upgrade'], handler: handleSlashUpgrade },
  { names: ['/restart'], handler: handleSlashRestart },
  { names: ['/keys', '/shortcuts'], handler: handleSlashKeys },
];
