import { swallow } from '../utils/log';
/**
 * plugin-changelog — Auto-generates CHANGELOG entries from completed tasks.
 * Appends entries to .makestudio/CHANGELOG.md in the repo.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { MakeStudioPlugin } from '../core/plugin-types';
import { TaskDispatch, TaskResult } from '../types';

const TASK_TYPE_LABELS: Record<string, string> = {
  feature: 'Added',
  test: 'Tests',
  database: 'Database',
  architecture: 'Changed',
  design: 'Design',
  infra: 'Infrastructure',
  planning: 'Planning',
};

const plugin: MakeStudioPlugin = {
  name: 'changelog',
  version: '1.0.0',
  description: 'Auto-generate CHANGELOG entries from completed tasks',

  hooks: {
    async afterTaskExec(task: TaskDispatch, result: TaskResult): Promise<void> {
      if (!result.gitInfo?.branch) return;

      try {
        const repoPath = process.cwd();
        const changelogDir = path.join(repoPath, '.makestudio');
        const changelogPath = path.join(changelogDir, 'CHANGELOG.md');
        fs.mkdirSync(changelogDir, { recursive: true });

        const now = new Date();
        const date = now.toISOString().split('T')[0];
        const time = now.toTimeString().split(' ')[0];
        const label = TASK_TYPE_LABELS[task.taskType || ''] || 'Changed';

        // Get files changed count
        let filesChanged = 0;
        try {
          const stat = execSync('git diff --shortstat HEAD~1 2>/dev/null || echo ""', {
            cwd: repoPath, encoding: 'utf8', stdio: 'pipe', timeout: 5_000,
          }).trim();
          const match = stat.match(/(\d+) files? changed/);
          if (match) filesChanged = parseInt(match[1], 10);
        } catch (err) { swallow(err); }

        const entry = [
          `### [${date} ${time}] ${label}: ${task.taskTitle || task.taskId}`,
          `- **Type:** ${task.taskType || 'unknown'}`,
          `- **Branch:** \`${result.gitInfo.branch}\``,
          `- **Cost:** $${result.costUsd.toFixed(4)}`,
          filesChanged > 0 ? `- **Files Changed:** ${filesChanged}` : '',
          '',
        ].filter(Boolean).join('\n');

        // Prepend to existing changelog or create new
        let existing = '';
        if (fs.existsSync(changelogPath)) {
          existing = fs.readFileSync(changelogPath, 'utf8');
        } else {
          existing = '# Changelog (Auto-generated by MakeStudio)\n\n';
        }

        // Insert after header
        const headerEnd = existing.indexOf('\n\n');
        if (headerEnd !== -1) {
          const header = existing.substring(0, headerEnd + 2);
          const body = existing.substring(headerEnd + 2);
          fs.writeFileSync(changelogPath, header + entry + '\n' + body, 'utf8');
        } else {
          fs.writeFileSync(changelogPath, existing + '\n' + entry, 'utf8');
        }
      } catch {
        // Non-fatal
      }
    },
  },
};

export default plugin;
